.vscode/launch.json
.vscode/settings.json
src/artemis/devices/fast_grid_scan.py
src/artemis/devices/motors.py
src/artemis/devices/system_tests/test_gridscan_system.py
src/artemis/devices/unit_tests/test_gridscan.py

See https://jira.diamond.ac.uk/browse/MXDGA-3724
To review:
* Confirm that the Fast Grid Scan device is doing everything required for https://jira.diamond.ac.uk/browse/MXGDA-3733
* Confirm unit tests run
* Note that the system tests will not work against s03 currently as the fast grid scan IOC is not running on it

MXDGA-3724: Added the MVP for the fast grid scan motion

---

Pipfile
Pipfile.lock

Fixes #6 
To test:
* Confirm on main zebra system tests fail with `NotImplementedError`
* Checkout this branch and re-install `pipenv install --dev`
* Confirm the zebra system tests now pass

6: Added pyepics to pipfile

---

src/artemis/devices/eiger.py
src/artemis/devices/eiger_odin.py
src/artemis/devices/system_tests/test_eiger_system.py

Fixes #25 
To test:
* Set up a monitor on Acquisition ID: `camonitor -S BL03S-EA-EIGER-01:OD:AcquisitionID`
* Run the Eiger system tests
* Confirm Acquisition ID gets set to the correct value and only once. e.g. not the behavior in https://github.com/DiamondLightSource/python-artemis/pull/23#issuecomment-1029060653

25: Correctly set filenames on ODIN to avoid doubly setting them

---

src/artemis/devices/backlight.py
src/artemis/snapshot_plan.py

Fixes #117 
To test:
* `pipenv run python artemis/snapshot_plan.py` moves the backlight

#117: Created device for backlight and start of snapshot plan

---

src/artemis/devices/undulator.py
src/artemis/fast_grid_scan_plan.py
src/artemis/ispyb/ispyb_dataclass.py
src/artemis/parameters.py
src/artemis/tests/test_fast_grid_scan_plan.py

Fixes #125
Undulator device tested using:
```
from bluesky import RunEngine
import bluesky.plan_stubs as bps
undulator = Undulator(name="Undulator", prefix="SR03I-MO-SERVC-01:")
def get_value():
gap = yield from bps.rd(undulator.gap)
print(gap)
RE = Runengine({})
RE(get_value())
```
Output was compared with the relevant PV using `caget SR03I-MO-SERVC-01:BLGAPMTR.RBV` and found to be consistent.
Changes needed on the GDA side:
- No longer pass undulator_gap parameter to artemis
- Need to pass insertion_prefix parameter to artemis

125 get undulator gap

---

run_artemis.sh
src/artemis/fast_grid_scan_plan.py
src/artemis/tests/test_fast_grid_scan_plan.py

Fixes #163
Current behaviour -
Will fail if --deploy is run and the user running the script is not in dls_dasc group due to file permissions. Permissions will ned changing to resolve this (although it may not be such a bad thing for dls_dasc to be the only group with permission to deploy new versions)
By default the script at the moment will both start and deploy a new Artemis version. --deploy and --start flags are used to only perform those actions. The other option I could think of would be to have the default action be just starting the server and have --deploy only deploy and use both tags (--deploy --start) to perform both actions.
The --stop flag will currently override the --start and --deploy flags and only stop the currently running artemis.
If any of these should/could be …

Startup bash script for deploying, stopping and starting Artemis

---

pyproject.toml
setup.cfg

Fixes an issue introduced in #190, whereby the coverage CI was slightly broken due to pytest not using setup.cfg as its configuration file.

Edit config files so that the correct coverage reports are produced

---

setup.cfg
src/artemis/tests/test_zocalo_interaction.py
src/artemis/zocalo_interaction.py

This avoids bluesky logs ending up in the Zocalo/data analysis graylog stream.
See also https://github.com/DiamondLightSource/python-artemis/issues/27
Add E501 to flake ignore: Since we are already relying on black to apply an appropriate max line length, and flake8 can sometimes disagree ignore this particular warning

Use artemis-specific zocalo environment

---

.gitignore
Pipfile
README.md
graylog/Dockerfile
graylog/tcp_input.json
run_artemis.sh
setup_graylog.sh
src/artemis/__main__.py
src/artemis/fast_grid_scan_plan.py
src/artemis/log.py
src/artemis/tests/test_log.py
src/artemis/tests/test_main_system.py

Fixes #27 
This should do the required changes of logging to graylog and into the correct beamline areas.
Along with this I have set up an input on the dls graylog called Artemis, and a stream called Artemis(MX DAQ). Currently the stream just accepts any messages in it from that input, but can be made more sophisticated as more things get added.
Before this is merged I'd like a better overview on what the Artemis Zocalo config is doing with regards to logging. It is no longer sending them to the MX analysis graylog stream thanks to Richards fix, however i'd like to configure it so they end up in the Artemis(MX DAQ) stream.

27 integrate with graylog

---

.github/workflows/code.yml

It was found that adding verbose logging to the `pip install` in the CI fixed the issue seen previously. Given https://github.com/DiamondLightSource/python-artemis/issues/258 is on the horizon I'm going to call this a temporary fix.

Attempt to fix CI

---

src/artemis/devices/eiger_odin.py

Fixes #305 
To test:
* Confirm this contains the same changes as https://github.com/DiamondLightSource/python-artemis/pull/281

305: Ensure reading PVs as strings when appropriate

---

fake_zocalo/README.rst
fake_zocalo/__main__.py
fake_zocalo/dls_start_fake_zocalo.sh
src/artemis/tests/test_zocalo_system.py

- consumes 'end_run()' message
- sends back "results" for dcgid 4
Fixes #312
1. Run `module load rabbitmq/dev` and fake zocalo main.py in one terminal
2. Run `module load dials/latest`, set artemis zocalo environment to `devrmq` and end run_end() and wait_for_result() from a python shell in another terminal and see that the request is "processed" and a "result" is returned.

#312 a very basic fake zocalo

---

src/artemis/tests/test_plan_system.py

Fixes #296
1. Follow the instructions in https://gitlab.diamond.ac.uk/controls/support/bl03s-builder/-/merge_requests/3 to get the slits IOC running
2. Run the new system test and confirm it passes

(#296) Added test for getting ispyb data

---

src/artemis/devices/eiger.py
src/artemis/devices/eiger_odin.py
src/artemis/devices/unit_tests/test_eiger.py
src/artemis/devices/unit_tests/test_odin.py

Fixes #395
1. Confirm that the explanation for the error seems plausible
2. Confirm creation of the status is moved earlier
3. Confirm the unit test passes

(#395) Move when we start waiting on filewriters

---

run_artemis.sh

1. Tested on beamline 
2. for local testing just confirm that the error message printed now shows the user/hostname when script is run

Fix checking for host/user in run_artemis

---

run_artemis.sh
src/artemis/__main__.py

Fixes #442
1. Confirm running `run_artemis` on a dev machine will run artemis up in dev mode, with appropriate warnings that it's doing so
2. Check in `./tmp/dev/artemis.txt` for signs that it's started up in dev mode correctly
3. Remove the change from https://github.com/DiamondLightSource/python-artemis/commit/ff1e647cc7137b741799207a75620a29e88be3b6 and add the following code to `__main__.py`:
```python
while True:
from time import sleep
sleep(0.1)
print("Hello")
```
4. `run_artemis.sh` and close the terminal you run it from
5. In a new terminal confirm artemis has died `ps -aux | grep artemis`
6. Reinstate https://github.com/DiamondLightSource/python-artemis/commit/ff1e647cc7137b741799207a75620a29e88be3b6 but keep the modifications in `__main__`
7. Repeat 4-5 but confirm artemis has …

442: Redirect stdout

---

.github/workflows/code.yml
.github/workflows/container_tests.sh
dls_dev_env.sh
setup.cfg

Fixes #399 
Replaces #407 
Randomises the order in which tests are run, including in CI, in order to help identify any interdependent tests.
0. see tests pass even in a random order

399 redo random order tests

---

setup.cfg

Fixes #337 
This issue was due to an error inside the `nexgen` package, which has been fixed in version 0.6.12. Unpinning should will get the latest version (currently 0.6.16) - which also checks that unused datasets are not used as sources for the VDS.

Fix incorrect sample depends_on value

---

src/artemis/external_interaction/__init__.py

as in title
Will let you do 
```python
from artemis.external_interaction import ZocaloInteractor
```
etc.

add external interaction classes to __init__

---

src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py
src/artemis/external_interaction/zocalo/zocalo_interaction.py

See python-dlstbx#196
1. Test artemis X-ray centring with latest version of Zocalo X-ray centring service
2. Confirm that artemis moves to the correct location

Zocalo no longer returns reversed coordinates

---

src/artemis/external_interaction/nexus/write_nexus.py
src/artemis/external_interaction/unit_tests/test_write_nexus.py

Fixes #436
1. check removal hasn't broken any tests

436 no longer clean unused links

---

src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py
src/artemis/external_interaction/zocalo/zocalo_interaction.py

Fixes #518 
I can't think of a brilliant way of testing this other than implementing the wait for run_status in fake_zocalo but I really don't want fake_zocalo to grow that much, particularly as we don't actually want the wait functionality.
1. Run test

Tell Zocalo to no longer wait on run status

---

src/artemis/experiment_plans/fast_grid_scan_plan.py

Fixes #535
1. Have added https://github.com/DiamondLightSource/python-artemis/issues/536 for a good test
1. In the mean time you can use:
```python
import bluesky.plan_stubs as bps
import bluesky.preprocessors as bpp
from bluesky import RunEngine
from bluesky.callbacks import CallbackBase
from ophyd import Device
class MyDevice(Device):
def unstage(self):
print("Unstaging")
class MyCallback(CallbackBase):
def stop(self, doc):
print("Stopped")
return super().stop(doc)
my_device = MyDevice(name="blah")
@bpp.set_run_key_decorator("do_fgs")
@bpp.run_decorator(md={"subplan_name": "do_fgs"})
@bpp.stage_decorator([my_device])
def my_plan():
yield from bps.sleep(1)
@bpp.subs_decorator(MyCallback())
def test_plan():
yield from my_plan()
RE = RunEngine()
RE(test_plan())
```
to test the concepts. …

Trigger zocalo after eiger has staged

---

src/artemis/devices/system_tests/test_aperturescatterguard_system.py
src/artemis/devices/unit_tests/test_eiger.py
src/artemis/external_interaction/system_tests/conftest.py
src/artemis/external_interaction/system_tests/test_zocalo_system.py
src/artemis/external_interaction/zocalo/zocalo_interaction.py
src/artemis/system_tests/test_fgs_plan.py

Fixes #545
1. Run system tests without fake_zocalo running
2. Confirm it times out after ~5 secs
3. Confirm `test_when_set_odin_pvs_called_then_full_filename_written` is less flaky
4. Confirm aperture/scatterguard tests are faster (can do this by running just these tests on main and here, I see ~60 sec speedup)

Zocalo will now timeout if no results are recieved - Additionally tidies up some tests

---

src/artemis/device_setup_plans/setup_zebra_for_rotation.py
src/artemis/devices/eiger.py
src/artemis/devices/zebra.py
src/artemis/system_tests/test_device_setups_and_cleanups.py

Fixes #524 
Adds a plan which sets up the zebra for rotation data collection. Has been tested on the beamline.
1. Run with S03 and check that the correct PVs are set to the correct values

524 setup zebra for rotation

---

src/artemis/external_interaction/callbacks/fgs/ispyb_callback.py
src/artemis/external_interaction/callbacks/fgs/tests/test_ispyb_handler.py
src/artemis/external_interaction/ispyb/store_in_ispyb.py
src/artemis/log.py

Fixes #541
2. Confirm messages in graylog have group id, e.g. https://graylog2.diamond.ac.uk/messages/logs_8179/ee540061-b3d2-11ed-bee7-1866dafae904

Add data collection group id to logs

---

fake_zocalo/dls_start_fake_zocalo.sh
src/artemis/parameters/constants.py
src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters.json
test_parameters.json

Fixes #556
1. On main run the system tests and search on graylog with your machine name e.g. https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1920&highlightMessage=&relative=7200&q=ws455
2. Confirm logs are getting sent to graylog
3. Switch to this branch
4. Clone https://gitlab.diamond.ac.uk/scisoft/zocalo/-/merge_requests/82 somewhere locally
5. In `zocalo_interaction.py` pass the modified config yaml e.g. `zc = zocalo.configuration.from_file("/scratch/ffv81422/zocalo/configuration.yaml")`
6. Repeat 1) and confirm no logging is happening anymore

Stops unit tests pushing to real graylog

---

.vscode/python-artemis.code-workspace
README.md
dls_dev_env.sh
pull_request_template.md
setup.cfg

Fixes #558
Also modifyed docs in https://github.com/DiamondLightSource/python-artemis/wiki/Getting-Started (note new way of running vscode and message on having to select interpretter).
See also updated release docs in https://github.com/DiamondLightSource/python-artemis/wiki/Creating-a-release-and-deploying-it. Ensure that this process sounds sensible
After this is merged we should stop using `dls_dev_env.sh` to install to production. We can either make a new issue or modify https://github.com/DiamondLightSource/python-artemis/pull/466.
1. Run `dls_dev_env.sh`
2. Run `code .vscode/python-artemis.code-workspace` and confirm a vscode session opens which works as expected

Set up dev tools to more easily work with dodal

---

run_artemis.sh
src/artemis/log.py
src/artemis/unit_tests/test_log.py

Fixes #497
Needs GDA changes in https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/38534
1. Add `raise Exception()` in the first line of `__main__.py`, this will cause Artemis to not be able to start
2. Confirm `run_artemis.sh` fails and produces nice logs in `./tmp/dev`
3. Run `artemis_restart()` on the jython console and when prompted give the path to your local artemis
4. Confirm with the error introduced in 1 it bombs out and that the logs are in the location GDA says they are
6. Remove the error in 1 and confirm `artemis_restart` is happy again

Actually check the state of Artemis when running

---

setup.cfg
src/artemis/experiment_plans/fast_grid_scan_plan.py
src/artemis/experiment_plans/full_grid_scan.py
src/artemis/experiment_plans/oav_grid_detection_plan.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_grid_detection_plan.py
src/artemis/parameters/beamline_parameters.py
src/artemis/parameters/constants.py
src/artemis/parameters/tests/test_external_parameters.py
src/artemis/system_tests/test_aperturescatterguard_system.py
src/artemis/system_tests/test_fgs_plan.py

Tidy up device creation for full grid scan

---

src/artemis/conftest.py
src/artemis/unit_tests/test_log.py

and uncomment tests
Fixes #644
1. see tests work I guess?

delete logging handlers in global test teardown

---

src/artemis/external_interaction/unit_tests/test_write_nexus.py

Fixes #677
1. Confirm tests fail after `pip install nexgen==0.6.26`
2. Confirm tests pass after `pip install nexgen==0.6.27`
3. Confirm commented issue will solve skipped test

Add test for writing nexus files early

---

setup.cfg
src/artemis/external_interaction/ispyb/ispyb_dataclass.py
src/artemis/parameters/internal_parameters/internal_parameters.py

Fixes 678
Makes all the internal param classes into pydantic models. Does not yet do it for InternalParameters because that is more complicated - new issue for this: https://github.com/DiamondLightSource/python-artemis/issues/681
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/68
1. Run tests

678 pydantic internal params

---

setup.cfg
src/artemis/conftest.py
src/artemis/device_setup_plans/unit_tests/test_zebra_setup.py
src/artemis/experiment_plans/fast_grid_scan_plan.py
src/artemis/experiment_plans/full_grid_scan.py
src/artemis/experiment_plans/oav_grid_detection_plan.py
src/artemis/experiment_plans/rotation_scan_plan.py
src/artemis/experiment_plans/tests/conftest.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_grid_detection_plan.py
src/artemis/experiment_plans/tests/test_rotation_scan_plan.py
src/artemis/system_tests/test_main_system.py

Needed for https://github.com/DiamondLightSource/dodal/issues/69

change i03 import paths

---

fake_zocalo/__main__.py
src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py
src/artemis/external_interaction/zocalo/zocalo_interaction.py

See https://github.com/DiamondLightSource/python-dlstbx/pull/215
1. Do grid scan
2. Confirm artemis correctly handles the new format of XRC result returned by zocalo

Updated zocalo message format

---

setup.cfg
src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py

Fixes #713 
tests were hanging on a magicmock status returned from eiger staging
To test, run tests. You could also check that they fail without these changes and bluesky 1.11.

Upgrade bluesky to 1.11

---

setup.cfg
src/artemis/__main__.py
src/artemis/experiment_plans/fast_grid_scan_plan.py
src/artemis/experiment_plans/full_grid_scan.py
src/artemis/experiment_plans/rotation_scan_plan.py
src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_rotation_scan_plan.py
src/artemis/system_tests/test_main_system.py

Fixes #656
Moves the creation of callback objects into the respective experiment plans, needed for future removal of `__main__.py` and more consistent between plans.
Coincidentally fixes some tests which shouldn't have worked.
1. Run tests

656 move callback creation to inside plan

---

src/artemis/parameters/plan_specific/grid_scan_with_edge_detect_params.py
src/artemis/parameters/plan_specific/tests/test_grid_scan_with_edge_detect_internal_parameters.py
src/artemis/parameters/schemas/full_external_parameters_schema.json
src/artemis/parameters/tests/test_data/good_test_grid_with_edge_detect_parameters.json
src/artemis/parameters/tests/test_data/good_test_parameters.json
src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters.json
test_parameter_defaults.json
test_parameters.json

Fixes #718 
Note this is based off https://github.com/DiamondLightSource/python-artemis/pull/721, ensure that PR is reviewed/merged first
1. Confirm new test passes and is sensible

Fix bug in API for grid scan with edge detection

---

src/artemis/experiment_plans/full_grid_scan.py
src/artemis/experiment_plans/tests/conftest.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py
src/artemis/parameters/plan_specific/grid_scan_with_edge_detect_params.py
src/artemis/parameters/plan_specific/tests/test_grid_scan_with_edge_detect_internal_parameters.py
src/artemis/parameters/schemas/full_external_parameters_schema.json
src/artemis/parameters/tests/test_data/good_test_grid_with_edge_detect_parameters.json
src/artemis/parameters/tests/test_data/good_test_parameters.json
src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters.json
test_parameter_defaults.json
test_parameters.json

Fixes https://github.com/DiamondLightSource/python-artemis/issues/674
Adds a unit test for `full_grid_scan`
Note: depends on https://github.com/DiamondLightSource/python-artemis/pull/722

Tests for full grid scan

---

src/artemis/parameters/constants.py
src/artemis/parameters/internal_parameters.py
src/artemis/parameters/tests/test_data/bad_test_parameters_wrong_version.json
src/artemis/parameters/tests/test_data/good_test_grid_with_edge_detect_parameters.json
src/artemis/parameters/tests/test_data/good_test_parameters.json
src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters.json
test_parameters.json

Fixes #741 
1. On main, in a directory that is not the top level `python-artemis` one, start an interpreter and run `from artemis.parameters.internal_parameters import ArtemisParameters`, confirm it fails
2. Do the same on this branch, confirm it passes

Remove defaults from ArtemisParameters

---

setup.cfg
src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_grid_detection_plan.py

Fixes #686 
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/92
The unit test seems to work but takes a long time to complete for some reason
Confirm unit test is sensible

Add testing for fast grid scan without grid detect

---

src/artemis/__main__.py
src/artemis/system_tests/test_main_system.py

Fixes #679
Note: this contains changes from https://github.com/DiamondLightSource/python-artemis/pull/722, that PR should be reviewed/merged first
The associated GDA change is https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/39268/3, please +2 this at the same time.
1. Confirm unit tests still all pass
2. Using the GDA change above set it up to talk to Artemis by adding the following properties:
```
gda.gridscan.artemis.enabled=true
gda.gridscan.artemis.grid.detection=true
gda.gridscan.artemis.flaskServerAddress=localhost:5005
gda.mx.callArtemisInDummyMode=true
```
3. Paste the following into the data collection table:
```
<?xml version="1.0" encoding="UTF-8"?>
<ExtendedCollectRequests>
<usingDna>false</usingDna>
<extendedCollectRequest>
<collect_request>
<fileinfo> …
```

GDA should use exception status from Artemis to work out if to continue

---

setup.cfg
src/artemis/experiment_plans/optimise_attenuation_plan.py
src/artemis/experiment_plans/tests/test_grid_detection_plan.py
src/artemis/experiment_plans/tests/test_optimise_attenuation_plan.py
src/artemis/system_tests/test_main_system.py

Fixes #754 
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/102
1. Confirm deadtime optimisation logic is the same of that in the GDA script mx-config/scripts/attenuation_optimiser.py, in the run_xspress3mini_optimisation_routine()
2. Confirm new tests run and are sensible

Add deadtime optimisation

---

setup.cfg

Fixes #774
1. Run `./dls_dev_env.sh` and confirm tests pass

Add pydantic dependency explicitly to artemis

---

src/artemis/experiment_plans/full_grid_scan.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py

Unstage detector if there is an issue in grid detection

---

setup.cfg
src/artemis/experiment_plans/fast_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py
src/artemis/external_interaction/ispyb/ispyb_dataclass.py
src/artemis/system_tests/test_main_system.py

Fixes #632 
Link to dodal PR (if required): [#113](https://github.com/DiamondLightSource/dodal/pull/113)
1. Check that all tests still pass

632 get flux from pv

---

src/artemis/experiment_plans/full_grid_scan.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py
src/artemis/parameters/plan_specific/tests/test_fgs_internal_parameters.py

Fixes #759
1. Run new tests against main, confirm they fail
2. Run against this branch, confirm they pass

Fix parameter issues in full_grid_scan

---

setup.cfg
src/artemis/experiment_plans/fast_grid_scan_plan.py
src/artemis/experiment_plans/full_grid_scan.py
src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py

Fixes #788 and fixes #791
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/121
1. Confirm tests cover original issue and pass

Ensure that eiger cleans up properly on error

---

src/artemis/experiment_plans/oav_grid_detection_plan.py
src/artemis/experiment_plans/tests/conftest.py
src/artemis/experiment_plans/tests/test_grid_detection_plan.py
src/artemis/experiment_plans/tests/test_rotation_scan_plan.py

Fixes #770
1. Confirm tests are sensible and pass

Correct the grid overlay drawing

---

src/artemis/device_setup_plans/unit_tests/test_zebra_setup.py
src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_grid_detection_plan.py
src/artemis/experiment_plans/tests/test_optimise_attenuation_plan.py
src/artemis/experiment_plans/tests/test_rotation_scan_plan.py
src/artemis/external_interaction/unit_tests/test_store_in_ispyb.py
src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py
src/artemis/system_tests/test_fgs_plan.py
src/artemis/system_tests/test_main_system.py
src/artemis/unit_tests/test_log.py

Fixes #812
1. Confirm tests all still pass and removed test is out of date

Use autospec in patches, also remove useless test

---

setup.cfg
src/artemis/__main__.py
src/artemis/parameters/plan_specific/grid_scan_with_edge_detect_params.py
src/artemis/system_tests/test_main_system.py

remove dataclasses_json

---

src/artemis/device_setup_plans/unit_tests/test_zebra_setup.py
src/artemis/system_tests/test_device_setups_and_cleanups.py

Fixes #843
Given the test is flaky I'm not sure we can reliably test this fixes the issue but I guess check if you agree that this is probably the issue

Fix flaky zebra tests

---

live_test_rotation_params.json
live_test_rotation_params_move_xyz.json
src/artemis/experiment_plans/rotation_scan_plan.py
src/artemis/external_interaction/ispyb/ispyb_dataclass.py
src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters_nomove.json

Fixes #847
Also changed the name of the validator to avoid confusion around how to get the variable out.
1. Confirm tests pass now

Fix transmission rename for rotation scans

---

setup.cfg
src/artemis/__main__.py
src/artemis/experiment_plans/fast_grid_scan_plan.py
src/artemis/external_interaction/callbacks/aperture_change_callback.py
src/artemis/external_interaction/callbacks/fgs/ispyb_callback.py
src/artemis/external_interaction/callbacks/oav_snapshot_callback.py
src/artemis/external_interaction/nexus/write_nexus.py
src/artemis/external_interaction/zocalo/zocalo_interaction.py

Fixes #810
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/123
1. Confirm class variables are removed and tests still pass
2. Confirm exceptions are listed in the issue

Ensure proper use of class variables

---

src/artemis/experiment_plans/rotation_scan_plan.py
src/artemis/experiment_plans/tests/test_rotation_scan_plan.py

Fixes #836 
1. Confirm new test passes

Use EPICS acceleration value when calculating rotation scan offsets

---

live_test_rotation_params.json
live_test_rotation_params_move_xyz.json
src/artemis/experiment_plans/full_grid_scan.py
src/artemis/experiment_plans/oav_grid_detection_plan.py
src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py
src/artemis/experiment_plans/tests/test_grid_detection_plan.py
src/artemis/parameters/plan_specific/grid_scan_with_edge_detect_params.py
src/artemis/parameters/schemas/experiment_schemas/grid_scan_with_edge_detect_params_schema.json
src/artemis/parameters/schemas/full_external_parameters_schema.json
src/artemis/parameters/tests/test_data/good_test_grid_with_edge_detect_parameters.json
src/artemis/parameters/tests/test_data/good_test_parameters.json
src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters.json
src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters_nomove.json
test_parameter_defaults.json
test_parameters.json

Allow specifying the grid size in microns

---

src/artemis/experiment_plans/tests/test_rotation_scan_plan.py

1. Confirm that unit tests now pass

Fix rotation plan tests

---

.github/pages/make_switcher.py
.github/workflows/code.yml
.github/workflows/linkcheck.yml
.gitignore
.pre-commit-config.yaml
.vscode/extensions.json
.vscode/settings.json
pyproject.toml
setup.cfg
src/hyperion/system_tests/test_fgs_plan.py

Test for adding `ruff` as a replacement for `flake8` + `isort`.
Main advantage is speed (approx 100x faster):
```
$ time isort --check .
real	0m0.420s
user	0m0.349s
sys	0m0.040s
$ time flake8 src/
real	0m0.859s
user	0m2.157s
sys	0m0.154s
$ time ruff .
real	0m0.011s
user	0m0.006s
sys	0m0.006s
```
One code change is required due to a difference in opinion between ruff and `isort` about constructs like:
```python
from somewhere import thing1
from somewhere import thing2 as aliased_name
from somewhere import thing3
```
which ruff prefers formatted as:
```python
from somewhere import thing1, thing3
from somewhere import thing2 as aliased_name
```
Other than that it is a 1:1 replacement in terms of linting rules.
This seems to be the direction a lot of modern python projects are moving in, and …

Idea: use `ruff` as a replacement for `flake8` + `isort` ?

---

src/hyperion/device_setup_plans/setup_oav.py
src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
src/hyperion/experiment_plans/oav_grid_detection_plan.py
src/hyperion/experiment_plans/tests/test_grid_detect_then_xray_centre_plan.py
src/hyperion/experiment_plans/tests/test_grid_detection_plan.py
src/hyperion/external_interaction/callbacks/grid_detection_callback.py
src/hyperion/external_interaction/callbacks/oav_snapshot_callback.py

Fixes #734 
Tests using:
```python
def _fake_grid_detection(
parameters: OAVParameters,
snapshot_template: str,
snapshot_dir: str,
grid_width_microns: float = 0,
box_size_um: float = 0.0
```
have been skipped by using `@pytest.mark.skip` as `_fake_grid_detection` does not have real enough parameters to pass the tests. I will raise a new issue for this.
1. Confirm (relevant) tests passes

734 grid using callbacks

---

src/hyperion/experiment_plans/flyscan_xray_centre_plan.py

Fixes #911 
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/185

#911 improve logging around setup

---

src/hyperion/experiment_plans/tests/test_flyscan_xray_centre_plan.py
src/hyperion/external_interaction/callbacks/ispyb_callback_base.py
src/hyperion/external_interaction/callbacks/xray_centre/tests/conftest.py

Fixes #913
Added `flux_flux_reading` into **test_flyscan_xray_centre_plan.py** mock subscriptions and **ispyb_callback_base.py** so flux can be properly read.
1. Run tests

913 flux is not being read from hardware

---

dls_dev_env.sh

Fixes #892
1. Run `./dls_dev_env.sh` on main, confirm you get a warning of `WARNING: Skipping dodal as it is not installed.`
2. Do the same on this branch, confirm no warning and that Hyperion is correctly using your local version of `dodal` by doing a `pip list`

Remove uninstall of dodal as it happens on re-install

---

setup.cfg
src/hyperion/experiment_plans/tests/test_flyscan_xray_centre_plan.py
src/hyperion/external_interaction/callbacks/rotation/nexus_callback.py
src/hyperion/external_interaction/callbacks/rotation/tests/test_rotation_callbacks.py
src/hyperion/external_interaction/callbacks/xray_centre/nexus_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/tests/test_nexus_handler.py
src/hyperion/external_interaction/nexus/nexus_utils.py
src/hyperion/external_interaction/nexus/write_nexus.py
src/hyperion/external_interaction/system_tests/test_write_rotation_nexus.py
src/hyperion/external_interaction/unit_tests/test_write_nexus.py

Fixes #887 
Writes `end_time_estimated` field in the nexus file at the same time as `start_time` instead of `end_time`, removing the need to reopen the file at the end of the collection.
This is also more in line with the NXmx standard.
1. Check tests relating to the nexus write/handler/callback still make sense and pass

Write end_time_estimated in nexus file

---

setup.cfg

Pin blueapi to version `0.3.7`, which doesn't depend on a specific dodal branch 
1. Try running `dls_dev_env.sh` and check that installation finishes correctly

Pin blueapi version

---

src/hyperion/__main__.py
src/hyperion/system_tests/test_main_system.py

Fixes #939 
On discussion with @DominicOram we decided just to remove the offending test as diagnosing the issue will take too much time, and we won't be using the blueskyrunner for much longer, and we know it works well on the beamline.
1. Run `pytest --random-order -m "not s03" a few times
2. Confirm tests in `test_main_system` don't fail

Fix flaky test_main_system tests

---

.gitignore
tests/unit_tests/external_interaction/test_write_rotation_nexus.py

Fixes #994
1. Run tests
2. Check if change is useful/makes sense

Use the tmpdir fixture for tests that create files

---

setup.cfg
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
src/hyperion/external_interaction/callbacks/grid_detection_callback.py
src/hyperion/parameters/plan_specific/grid_scan_with_edge_detect_params.py
src/hyperion/parameters/plan_specific/pin_centre_then_xray_centre_params.py
src/hyperion/parameters/schemas/experiment_schemas/grid_scan_params_schema.json
src/hyperion/parameters/schemas/experiment_schemas/grid_scan_with_edge_detect_params_schema.json
src/hyperion/parameters/schemas/full_external_parameters_schema.json
tests/test_data/parameter_json_files/good_test_grid_with_edge_detect_parameters.json
tests/test_data/parameter_json_files/good_test_parameters.json
tests/test_data/parameter_json_files/good_test_pin_centre_then_xray_centre_parameters.json
tests/test_data/parameter_json_files/good_test_rotation_scan_parameters.json
tests/test_data/parameter_json_files/good_test_rotation_scan_parameters_nomove.json
tests/test_data/parameter_json_files/good_test_stepped_grid_scan_parameters.json
tests/test_data/parameter_json_files/live_test_rotation_params.json
tests/test_data/parameter_json_files/live_test_rotation_params_move_xyz.json
tests/test_data/parameter_json_files/test_parameter_defaults.json
tests/test_data/parameter_json_files/test_parameters.json
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_grid_detection_plan.py

Fixes #1010 
Dodal PR at https://github.com/DiamondLightSource/dodal/pull/251
Please also review https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40665 at the same time
I'm not a big fan of passing this all the way down like this, especially as we have to then put it in dodal. But hopefully its a temporary measure, open to better suggestions though.

Allow disabling stub offsets

---

src/hyperion/external_interaction/ispyb/store_in_ispyb.py

Fixes #1024
Updates the field we write to, corresponding to [recent ispyb-api updates](https://github.com/DiamondLightSource/ispyb-api/commit/491c126bda3fb37328509b7108853a1c92881de5).
You might need to `pip install --upgrade ipsyb` or redeploy the venv for this to work locally.
1. Run tests

#1024 Update store_in_ispyb to use micronsPerPixel

---

src/hyperion/experiment_plans/wait_for_robot_load_then_centre.py
src/hyperion/external_interaction/ispyb/ispyb_dataclass.py
src/hyperion/parameters/plan_specific/wait_for_robot_load_then_center_params.py
src/hyperion/parameters/schemas/experiment_schemas/wait_for_robot_load_then_centre_schema.json
src/hyperion/parameters/schemas/full_external_parameters_schema.json
tests/test_data/parameter_json_files/good_test_wait_for_robot_load_params.json
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py

Fixes #1031 
We need to revisit how we do some of this, there's a bunch of boilerplate here that isn't required at all but that seems out of scope of this
1. Confirm unit tests pass.

Add boilerplate code for wait_for_robot_load_then_centre

---

src/hyperion/snapshot_plan.py
tests/system_tests/experiment_plans/test_plan_system.py
tests/unit_tests/device_setup_plans/test_setup_oav.py
tests/unit_tests/device_setup_plans/test_topup_plan.py
tests/unit_tests/device_setup_plans/test_utils.py
tests/unit_tests/device_setup_plans/test_xbpm_feedback.py
tests/unit_tests/experiment_plans/test_grid_detection_plan.py
tests/unit_tests/experiment_plans/test_optimise_attenuation_plan.py
tests/unit_tests/experiment_plans/test_pin_tip_centring.py
tests/unit_tests/experiment_plans/test_rotation_scan_plan.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py

1. Run `pyright .` on main and here
2. Confirm number of failures reduced
3. Confirm no behaviour change

Fixed some type errors

---

src/hyperion/__main__.py
src/hyperion/experiment_plans/__init__.py
src/hyperion/experiment_plans/experiment_registry.py
src/hyperion/experiment_plans/wait_for_robot_load_then_centre_plan.py
src/hyperion/external_interaction/callbacks/ispyb_callback_base.py
src/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py
src/hyperion/parameters/plan_specific/wait_for_robot_load_then_center_params.py
src/hyperion/utils/context.py
tests/system_tests/hyperion/test_main_system.py
tests/test_data/parameter_json_files/good_test_wait_for_robot_load_params.json
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py

Fixes #1049
1. Confirm tests run
1. Start hyperion
```
export BEAMLINE=i03
python -m hyperion --dev --skip-startup-connection
```
In another terminal run an xray centre then robot load plan: `curl -X PUT http://127.0.0.1:5005/wait_for_robot_load_then_centre/start --data-binary "@tests/test_data/parameter_json_files/good_test_wait_for_robot_load_params.json" -H "Content-Type: application/json"`. Confirm this gives a success

Fix issues in robot load found in testing

---

src/hyperion/external_interaction/callbacks/ispyb_callback_base.py
src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/zocalo_callback.py
src/hyperion/external_interaction/ispyb/ispyb_utils.py
src/hyperion/external_interaction/ispyb/store_datacollection_in_ispyb.py
tests/system_tests/external_interaction/conftest.py
tests/system_tests/external_interaction/test_ispyb_dev_connection.py
tests/unit_tests/experiment_plans/conftest.py
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
tests/unit_tests/external_interaction/callbacks/xray_centre/conftest.py
tests/unit_tests/external_interaction/callbacks/xray_centre/test_ispyb_handler.py
tests/unit_tests/external_interaction/callbacks/xray_centre/test_zocalo_handler.py
tests/unit_tests/external_interaction/test_ispyb_utils.py
tests/unit_tests/external_interaction/test_store_datacollection_in_ispyb.py

Part of #1017 
Robot load ispyb entries are very different to data collection ones. This code takes the common parts out and puts them in a utils class.
1. Confirm behavior is broadly unchanged
2. Confirm unit tests still pass

Move common parts out of store in ispyb and rename

---

tests/unit_tests/experiment_plans/test_grid_detection_plan.py
tests/unit_tests/experiment_plans/test_pin_tip_centring.py

Fixes #1050
1. Run `pytest -m "not s03" --durations=0` on main
2. Run on this branch, confirm tests still pass but are ~10s faster

Speed up unit tests

---

pyproject.toml
tests/system_tests/experiment_plans/test_fgs_plan.py
tests/system_tests/external_interaction/test_zocalo_system.py

Using the `import-mode=importlib` option hides a number of legitimate errors for me and for CI (though interestingly not for @rtuck99). In particular it hides the bad `IspybIds` import that this fixes. I'm not sure why we added this option in in the first place @dperl-dls as it seems to work w/o it?

Remove using import-mode=importlib for tests and add required __init__ files

---

src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
src/hyperion/external_interaction/ispyb/store_datacollection_in_ispyb.py
tests/unit_tests/external_interaction/test_store_datacollection_in_ispyb.py

Fixes #1072 fixes #1080
- Adds ZocaloResults stage call which wipes old results from the queue
- Rounds ISPyB comment box sizes to 1DP
Link to dodal PR (if required): [#297](https://github.com/DiamondLightSource/dodal/pull/297)
1. Run tests

Discard old processing results

---

src/hyperion/__main__.py
tests/conftest.py
tests/unit_tests/hyperion/test_main_system.py

- Properly destroys the `RunEngine` after each test
- stops some classes holding state they shouldn't
Maybe fixes that flaky test, who knows. I ran the tests a little over 50 times with
```bash
for i in {0..50}; do 
pytest --random-order -m "not s03";
if [ $? -ne 0 ]; then 
break; 
fi; 
done
```
and didn't get any failures.

Fix flaky main system test

---

setup.cfg
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
tests/conftest.py

Required for https://github.com/DiamondLightSource/dodal/pull/300
1. Run tests against version of dodal in linked PR

add unstage for zocalo

---

setup.cfg
src/hyperion/device_setup_plans/utils.py
tests/unit_tests/device_setup_plans/test_utils.py

Fixes #1046
Link to dodal PR (if required):N/A
1. Eiger should now disarm if detector move fails or if the shutter fails to open. Note that the detector position and shutter state are not restored.

(#1046) Fix eiger not disarming if detector setup fails

---

.vscode/launch.json
run_hyperion.sh
src/hyperion/__main__.py
src/hyperion/experiment_plans/experiment_registry.py
src/hyperion/external_interaction/callbacks/abstract_plan_callback_collection.py
src/hyperion/parameters/cli.py
tests/conftest.py
tests/system_tests/hyperion/test_main_system.py
tests/unit_tests/hyperion/test_main_system.py

Fixes #1073
Requires GDA change https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/40900 to take effect, but shouldn't break anything on its own
1. Run tests
2. Run `hyperion_restart()` from GDA (with the above change applied) and see that hyperion is started with the external callbacks turned off

1073 make external callbacks optional

---

src/hyperion/external_interaction/callbacks/ispyb_callback_base.py
src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
src/hyperion/external_interaction/ispyb/store_datacollection_in_ispyb.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
tests/unit_tests/external_interaction/test_store_datacollection_in_ispyb.py

Fixes #920 
`RotationIspybCallback` now holds on to the previous experiment's sampleID, and if the next one matches, reuses the DCGID for the ISPYB deposition
1. Run tests

920 Combine rotations in ispyb

---

tests/conftest.py
tests/unit_tests/experiment_plans/test_rotation_scan_plan.py

Fixes #1111
1. Tests are tidier
2. Tests still pass and are functionally the same

Tidy up rotation tests to use common composites from fixture

---

src/hyperion/external_interaction/nexus/write_nexus.py
tests/unit_tests/external_interaction/test_write_nexus.py

Fixes #1139
1. Confirm new test fails on main and passes here
2. Confirm there are no type errors in `test_write_nexus.py` and functionality unchanged other than new test

Use proper beamline name in nexus

---

setup.cfg
tests/unit_tests/external_interaction/ispyb/conftest.py

Fixes #1163 
Link to dodal PR (if required): DiamondLightSource/dodal#346
1. Comments in ispyb should now have the correct coordinate for the bottom-right which was previously incorrect

(#1163) Fix for ispyb comment coordinates being wrong due to pixels-per-micron/microns-per-pixel

---

setup.cfg
src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
src/hyperion/external_interaction/ispyb/ispyb_dataclass.py
src/hyperion/external_interaction/ispyb/rotation_ispyb_store.py
src/hyperion/parameters/schemas/full_external_parameters_schema.json
src/hyperion/parameters/schemas/ispyb_parameters_schema.json
tests/test_data/parameter_json_files/good_test_grid_with_edge_detect_parameters.json
tests/test_data/parameter_json_files/good_test_parameters.json
tests/test_data/parameter_json_files/good_test_pin_centre_then_xray_centre_parameters.json
tests/test_data/parameter_json_files/good_test_rotation_scan_parameters.json
tests/test_data/parameter_json_files/good_test_rotation_scan_parameters_nomove.json
tests/test_data/parameter_json_files/good_test_stepped_grid_scan_parameters.json
tests/test_data/parameter_json_files/good_test_wait_for_robot_load_params.json
tests/test_data/parameter_json_files/good_test_wait_for_robot_load_params_no_energy.json
tests/test_data/parameter_json_files/live_test_rotation_params.json
tests/test_data/parameter_json_files/live_test_rotation_params_move_xyz.json
tests/test_data/parameter_json_files/panda_test_parameters.json
tests/test_data/parameter_json_files/test_internal_parameter_defaults.json
tests/test_data/parameter_json_files/test_parameter_defaults.json
tests/test_data/parameter_json_files/test_parameters.json
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
tests/unit_tests/external_interaction/ispyb/test_rotation_ispyb_store.py

Fixes #1182
* ispyb experiment_type field should now be populated via the `ispyb_params.ispyb_experiment_type` field as specified by the call from GDA (for rotation scans)
* For gridscans it will be left as "mesh" or "Mesh3D" as appropriate, and if unspecified for rotation scans it will be "SAD"

Allow the ispyb experiment_type field to be populated by GDA

---

src/hyperion/device_setup_plans/setup_panda.py
tests/unit_tests/device_setup_plans/test_setup_panda.py

Fixes #1178
1. Check changes in hyperion arm, disarm, and trigger the PCAP block at the correct points
2. Confirm that the pcap.gate and pcap.trigger settings in https://gitlab.diamond.ac.uk/mx/i03-config/-/blob/main/panda_configs/flyscan_with_pcap.yaml?ref_type=heads are consistent with what the linked issue describes, and confirm that these are sensible

Panda grid scans: Set up position capture

---

setup.cfg
src/hyperion/device_setup_plans/manipulate_sample.py
src/hyperion/device_setup_plans/position_detector.py
src/hyperion/device_setup_plans/utils.py
src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
src/hyperion/experiment_plans/rotation_scan_plan.py
src/hyperion/experiment_plans/wait_for_robot_load_then_centre_plan.py
src/hyperion/external_interaction/ispyb/ispyb_dataclass.py
src/hyperion/parameters/schemas/ispyb_parameters_schema.json
tests/conftest.py
tests/system_tests/experiment_plans/test_rotation_plan.py
tests/test_data/parameter_json_files/good_test_wait_for_robot_load_params.json
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_pin_centre_then_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py
tests/unit_tests/external_interaction/nexus/test_write_nexus.py
tests/unit_tests/parameters/plan_specific/test_fgs_internal_parameters.py
tests/unit_tests/parameters/plan_specific/test_grid_scan_with_edge_detect_internal_parameters.py
tests/unit_tests/parameters/plan_specific/test_rotation_internal_parameters.py

Fixes #1077 
Link to dodal PR (if required): DiamondLightSource/dodal#296
Link to GDA Gerrit change: https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/41000
1. It should be possible for wait_for_robot_load_then_centre_plan to populate the ispyb resolution without requiring the parameter to be specified in the hyperion request.

1077 hyperion to populate ispyb params resolution instead of gda

---

src/hyperion/external_interaction/callbacks/common/ispyb_mapping.py
src/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/ispyb_mapping.py
tests/system_tests/external_interaction/conftest.py
tests/unit_tests/external_interaction/callbacks/xray_centre/test_ispyb_mapping.py
tests/unit_tests/external_interaction/ispyb/conftest.py
tests/unit_tests/external_interaction/ispyb/test_gridscan_ispyb_store_2d.py
tests/unit_tests/external_interaction/ispyb/test_gridscan_ispyb_store_3d.py

Moves more info into `GridScanInfo` and so simplifies a lot of other code, the new `GridScanInfo` is also a realistic packet of data that we could put into a Blueksy event so prepares us for that. Tests are broken in the same way as they are in base PR.

The great ispyb interaction refactor doms suggestion

---

tests/conftest.py
tests/unit_tests/experiment_plans/test_grid_detection_plan.py
tests/unit_tests/experiment_plans/test_optimise_attenuation_plan.py

Unit tests were being slowed down, mainly by a series of exceptions thrown after completion in `test_optimise_attenuation_plan`, caused by a Status timeout. This fixes the issue by initialising the fake PV to the expected value, causing the dodal device set not to time out.
It is still unclear what is the primary cause of the delay, but there seems to be a ~0.5s penalty for every exception reported on the RunEngine, and several other cases where exceptions are thrown after a test completes successfully, however none as significant as this.
On my machine, the following speedup was obtained:
Before fix, tests tooks
66.19, 65.47, 65.60 seconds
After fix:
29.38, 29.61, 29.60 seconds
The other fix here is to ensure that the RunEngine event loop is properly shut down after use. Unfortunately …

Speed up the unit tests

---

setup.cfg
src/hyperion/device_setup_plans/setup_oav.py
src/hyperion/experiment_plans/oav_grid_detection_plan.py
src/hyperion/experiment_plans/pin_tip_centring_plan.py
tests/unit_tests/device_setup_plans/test_setup_oav.py
tests/unit_tests/experiment_plans/test_grid_detection_plan.py
tests/unit_tests/experiment_plans/test_pin_centre_then_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_pin_tip_centring.py

Fixes #1068 and maybe #1213
Link to dodal PR: #https://github.com/DiamondLightSource/dodal/pull/358
Once we are confident in this change we should remove the resulting dead code: https://github.com/DiamondLightSource/hyperion/issues/1219
Tested on beamline and seems to work:
https://graylog2.diamond.ac.uk/streams/631745613d8af00a49bfee55/search?rangetype=absolute&fields=message%2Csource&width=1500&highlightMessage=&from=2024-03-05T13%3A41%3A38.000Z&to=2024-03-05T13%3A41%3A44.000Z&q=
https://ispyb.diamond.ac.uk/dc/visit/cm37235-1/dcg/11423343
1. Run tests

Use ophyd oav edge detetion for grid determination

---

dls_dev_env.sh

Fixes #1224 
1. Create a new env from this branch (using `dls_dev_env` and see that the warnings do not appear

Update pip and install wheel before environment setup

---

run_hyperion.sh
src/hyperion/parameters/constants.py

Fixes #865
1. Confirm `test_ispyb_get_comment_from_collection_correctly` still passes
2. Other ispyb system tests should also pass but are failing on main. Won't fix as the soon to be merged  ispyb refactor is going to change it all anyway

Rename ispyb credentials file

---

src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/rotation_scan_plan.py
src/hyperion/external_interaction/callbacks/__main__.py
src/hyperion/external_interaction/callbacks/log_uid_tag_callback.py
src/hyperion/log.py
src/hyperion/parameters/constants.py
tests/unit_tests/hyperion/test_log/test_log.py

1. See that `test_messages_are_tagged_with_run_uid` still passes even without the plan metadata

#1132 Remove need for metadata tag for logs

---

setup.cfg
src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py
tests/conftest.py

Fixes https://github.com/DiamondLightSource/hyperion/issues/1235
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/366

Use an extended epics motor for additional fields

---

.github/workflows/pin_versions.py
.github/workflows/test_data/pip_freeze.txt
.github/workflows/test_data/setup.cfg
.github/workflows/test_data/setup.cfg.pinned
.github/workflows/test_data/setup.cfg.unpinned
.github/workflows/test_pin_versions.py

Fixes #1254 
Link to dodal PR (if required): N/A
1. Run the pre-release-workflow and do a build
2. The pre-release-workflow and build succeeds

(#1254) Fix issue with prerelease build workflow

---

.github/workflows/code.yml
README.md
conftest.py
tests/conftest.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
tests/unit_tests/external_interaction/test_write_rotation_nexus.py

Fixes #1220
* Removes logging by default, as discussed on issue
* Also speeds up a few other tests
1. Run the tests with `pytest -m "not s03"`, confirm they all pass in ~30s
2. Confirm the tests in CI are still getting all the logs written to terminal

Speed up unit tests and fix some typing issues

---

setup.cfg
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
tests/conftest.py
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py

Fixes #1239 
The associated dodal change makes the FGS kickoff wait for there to be nothing running
This change makes the grid scan plan wait for the kickoff
Link to dodal PR (if required): [#380](https://github.com/DiamondLightSource/dodal/pull/380)
1. Run tests

Make plan wait on FGS kickoff

---

src/hyperion/experiment_plans/rotation_scan_plan.py
src/hyperion/external_interaction/callbacks/rotation/nexus_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/nexus_callback.py
src/hyperion/external_interaction/nexus/nexus_utils.py
src/hyperion/external_interaction/nexus/write_nexus.py
tests/conftest.py
tests/unit_tests/external_interaction/callbacks/xray_centre/test_nexus_handler.py
tests/unit_tests/external_interaction/nexus/test_write_nexus.py
tests/unit_tests/external_interaction/test_write_rotation_nexus.py

Fixes #1173
Removes any dependency that Nexus writing has on `ispyb_params`.
Note that this does mean that the nexus file is only written when all this data comes in, which is at a different point for rotations/grids. I think if we do https://github.com/DiamondLightSource/hyperion/issues/1245 then we're pretty close to being able to have one nexus callback for both
1. Confirm no reference to ispyb_params in nexus callbacks
2. Confirm tests are comprehensive and pass

Use event data for nexus writing

---

src/hyperion/experiment_plans/robot_load_then_centre_plan.py
tests/conftest.py
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py

Fixes #1265
1. Confirm new unit test passes

Prepare for robot load

---

src/hyperion/external_interaction/callbacks/__main__.py
tests/unit_tests/external_interaction/callbacks/test_external_callbacks.py

Fixes #1252 
1. Confirm change fixes issue and change to test is sensible

Initialise dodal logger in external callbacks

---

tests/conftest.py
tests/unit_tests/hyperion/test_log/conftest.py
tests/unit_tests/hyperion/test_log/test_log.py

Fixes unit test failures introduced in previous fix for #1252
1. CI tests pass

(#1252) Fix logging unit test failure

---

README.md
src/hyperion/__main__.py
src/hyperion/external_interaction/callbacks/__main__.py
src/hyperion/log.py
tests/system_tests/external_interaction/callbacks/test_external_callbacks.py

Fixes #1201, fixes #1208
1. Run dev hyperion and execute: `curl -X PUT http://127.0.0.1:5005/flush_debug_log` and see that this works
2. Check readme changes make sense

Add an endpoint to write `DEBUG` level logs

---

tests/unit_tests/device_setup_plans/test_setup_panda.py

1. Confirm unit tests pass (where they don't on main)

Fix unit test due to dodgy merge

---

src/hyperion/experiment_plans/robot_load_then_centre_plan.py
src/hyperion/external_interaction/callbacks/ispyb_callback_base.py
src/hyperion/external_interaction/ispyb/ispyb_dataclass.py
src/hyperion/parameters/plan_specific/rotation_scan_internal_params.py
src/hyperion/parameters/schemas/ispyb_parameters_schema.json
tests/system_tests/experiment_plans/test_fgs_plan.py
tests/system_tests/external_interaction/callbacks/test_external_callbacks.py
tests/test_data/hyperion_parameters.json
tests/test_data/parameter_json_files/bad_test_parameters_wrong_version.json
tests/unit_tests/experiment_plans/test_rotation_scan_plan.py
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
tests/unit_tests/external_interaction/conftest.py
tests/unit_tests/external_interaction/test_ispyb_dataclass.py
tests/unit_tests/external_interaction/test_write_rotation_nexus.py
tests/unit_tests/parameters/test_internal_parameters.py

Fixes #1292
1. Confirm all instances of `current_energy_ev` are removed
2. Confirm all instances of `ispyb_params.transmission_fraction` are removed
3. Confirm all instances of `ispyb_params.flux` are removed
4. Confirm tests still pass (other than the known failure in https://github.com/DiamondLightSource/hyperion/pull/1296)

Remove redundant ispyb params param

---

utility_scripts/deploy/deploy_hyperion.py

Fixes #1299
1. deploying a release from dev workspace as per the wiki should now work even if you have other tags in your git repository

(#1299) Add regex filter to include only build tags in the deployment script

---

tests/unit_tests/hyperion/test_main_system.py

Fixes #1257 
Link to dodal PR (if required): #XXX
1. Confirm this was the issue

Setup devices in sim mode during tests

---

setup.cfg
src/hyperion/external_interaction/nexus/nexus_utils.py
src/hyperion/external_interaction/nexus/write_nexus.py

Fixes #1321 
Merge together with creating a new Nexgen release
Note: tests are expected to fail (with `ImportError`s from nexgen) against the current release or older version of nexgen
1. See tests pass with nexgen main

(#1321) Update references to nexgen modules

---

.github/workflows/code.yml
.github/workflows/linkcheck.yml
.github/workflows/pre_release_workflow.yml
Dockerfile
README.md
setup.cfg
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/pin_centre_then_xray_centre_plan.py
src/hyperion/experiment_plans/rotation_scan_plan.py
utility_scripts/deploy/deploy_hyperion.py
utility_scripts/dls_dev_env.sh

Fixes #1324
Also fix a minor issue in `deploy_hyperion.py` wrt parsing of tags to versions when they aren't formatted as such
Acceptance criteria
CI runs with only python 3.11
the deploy script installs with 3.11
references to older python versions (e.g. in setup.cfg are removed)
this policy is documented in ``README`
there is an issue for moving to 3.12 when compatible ophyd-async/p4p are available
Link to GH issue for Python 3.12 is #1329

(#1324) Update python version to 3.11

---

setup.cfg
src/hyperion/experiment_plans/robot_load_then_centre_plan.py
src/hyperion/external_interaction/callbacks/robot_load/ispyb_callback.py
src/hyperion/external_interaction/ispyb/exp_eye_store.py
tests/conftest.py
tests/system_tests/external_interaction/test_exp_eye_dev.py
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py
tests/unit_tests/external_interaction/callbacks/robot_load/test_robot_load_ispyb_callback.py
tests/unit_tests/external_interaction/ispyb/test_expeye_interaction.py

Fixes #1282
Dodal PR: https://github.com/DiamondLightSource/dodal/pull/468
2. Run the modified system tests and confirm data appears in the dev ispyb database with snapshots (note https://jira.diamond.ac.uk/browse/LIMS-1304)

Take snapshots before robot load

---

setup.cfg
src/hyperion/device_setup_plans/setup_panda.py
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/robot_load_then_centre_plan.py
tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py

* Change references from PandA to HDFPanda
* Apply directory path from params
Fixes DiamondLightSource/dodal#466
Link to dodal PR (if required): DiamondLightSource/dodal#477
1. Tests pass
2. Hyperion now saves HDF files in the location specified by the `storage_directory` request parameter

Add panda support for writing positions

---

src/hyperion/device_setup_plans/setup_panda.py
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py
src/hyperion/parameters/constants.py

Fixes #1338 and #1200
I didn't add tests here since it was mainly just logging / I'm being a bit lazy, I can add some if needed though
1. Confirm changes are sensible and that tests pass

Panda improvements

---

setup.cfg
src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py

Fixes #1355 
Link to dodal PR (if required): #[505](https://github.com/DiamondLightSource/dodal/pull/505)
This ensures that the DirectoryProvider is a singleton that will reliably be shared between all devices if e.g. copying a detector from an existing beamline. It also exposes it to the pre-processor that is being used for configuring devices per-Run.
1. Check that PandA would write into correct directory for parameters if it wrote to a directory

 Convert UDCDirectoryProvider to standard pattern

---

src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py
src/hyperion/external_interaction/ispyb/data_model.py
src/hyperion/external_interaction/ispyb/ispyb_store.py
src/hyperion/parameters/components.py
src/hyperion/parameters/gridscan.py
src/hyperion/parameters/rotation.py
tests/system_tests/external_interaction/conftest.py
tests/system_tests/external_interaction/test_ispyb_dev_connection.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
tests/unit_tests/external_interaction/ispyb/conftest.py
tests/unit_tests/external_interaction/ispyb/test_rotation_ispyb_store.py

Fixes #1360 
Ensures ispyb experiment type is correctly passed along from parameters
1. Confirm updated test now checks the right thing

Correctly handle passed-in ISPyB experiment type (i.e. "characterization")

---

setup.cfg
utility_scripts/deploy/create_venv.py
utility_scripts/deploy/deploy_hyperion.py
utility_scripts/deploy/test_deploy.py

Fixes #1103 
Now uses `subprocess` to SSH, so that it only asks for the password if it needs it
1. Confirm deploy script in dev mode still works as expected, using `python deploy_hyperion.py "dev"` (NOTE: this won't actually work until we make a release with this change merged in, since the script will search the latest release for the file created in this PR)
2. We don't have unit tests for the deploy script, so test live on beamline for next deployment

Make deploy script create venv while SSH'd into control machine

---

setup.cfg
tests/conftest.py
tests/system_tests/external_interaction/test_ispyb_dev_connection.py
tests/unit_tests/device_setup_plans/test_setup_oav.py
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py
tests/unit_tests/external_interaction/callbacks/robot_load/test_robot_load_ispyb_callback.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py

Fixes https://github.com/DiamondLightSource/hyperion/issues/1376
Link to dodal PR (if required): [#525](https://github.com/DiamondLightSource/dodal/pull/525)
1. Confirm changes are sensible and that tests pass

Compatibility with ophyd async 0.3a4

---

tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py

There are a few issues with our tests and we lost some imports somewhere. Tests in this branch currently pass except for `test_rotation_scan_nexus_output_compared_to_existing_full_compare`, which I also couldn't get to pass in older hyperion commits
1. Do thing x
2. Confirm thing y happens

Fix import issues in tests

---

src/hyperion/parameters/components.py
tests/unit_tests/parameters/test_parameter_model.py

Fixes #1387
1. If the snapshot directory parameter is specified in the request then this path will be used to store the snapshots

(#1387) snapshot_directory request parameter can now be optionally specified

---

setup.cfg
src/hyperion/parameters/components.py
src/hyperion/parameters/constants.py
src/hyperion/parameters/gridscan.py
src/hyperion/parameters/rotation.py
tests/test_data/parameter_json_files/good_test_grid_with_edge_detect_parameters.json
tests/test_data/parameter_json_files/good_test_pin_centre_then_xray_centre_parameters.json
tests/test_data/parameter_json_files/good_test_rotation_scan_parameters.json
tests/test_data/parameter_json_files/good_test_rotation_scan_parameters_nomove.json
tests/test_data/parameter_json_files/ispyb_gridscan_system_test_parameters.json
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py

Fixes #1307 
This change removes the `detector` attribute from the Hyperion request parameters
Link to dodal PR (if required): DiamondLightSource/dodal#588
1. Tests still pass
2. Confirm thing y happens

1307 remove detector parameter from hyperion request parameters

---

setup.cfg
src/hyperion/device_setup_plans/xbpm_feedback.py
tests/system_tests/experiment_plans/test_fgs_plan.py
tests/unit_tests/device_setup_plans/test_xbpm_feedback.py
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_set_energy_plan.py

Fixes DiamondLightSource/dodal#229
Link to dodal PR (if required): DiamondLightSource/dodal#626
1. Tests still pass

(DiamondLightSource/dodal#229) Fix unit tests after converting xbpm_feedback to ophyd_async

---

tests/unit_tests/parameters/test_parameter_model.py

Fixes #1459 
The actual issue was already fixed previously, this is just a test to make sure that the issue described is no longer an issue. Inspection of the GDA params reveals no hardcoded values.

(#1459) test oscillation in rotationparams

---

src/hyperion/external_interaction/callbacks/common/ispyb_mapping.py
src/hyperion/external_interaction/callbacks/ispyb_callback_base.py
src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
src/hyperion/external_interaction/callbacks/rotation/ispyb_mapping.py
src/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/ispyb_mapping.py
tests/system_tests/external_interaction/test_ispyb_dev_connection.py
tests/unit_tests/experiment_plans/test_rotation_scan_plan.py
tests/unit_tests/external_interaction/callbacks/conftest.py
tests/unit_tests/external_interaction/callbacks/xray_centre/test_ispyb_callback.py

Fixes #1327 and fixes #1454
Gridscans should now read populate the `omega_start` and `axis_start` values in ispyb by reading the smargon omega directly during grid detection when snapshots are taken.
The corresponding changes for rotations will be made in a separate PR ~as this depends on #1443~
Note that the values will be inverted from previous as they are taken from hardware; this change should be temporary until #1391 is fixed
1. Tests pass
2. ispyb reports correct `omega_start`/`axis_start`/`axis_range`/`axis_end` values

(#1327) ispyb omega_start, axis_start now read from hardware for gridscans

---

.pre-commit-config.yaml

Fixes pre-commit hooks for the changed ruff syntax (as opposed to CI)

Fix pre-commit hooks for new ruff syntax

---

setup.cfg
src/hyperion/device_setup_plans/smargon.py
src/hyperion/experiment_plans/pin_tip_centring_plan.py
src/hyperion/experiment_plans/rotation_scan_plan.py
src/hyperion/external_interaction/callbacks/grid_detection_callback.py
src/hyperion/external_interaction/callbacks/ispyb_callback_base.py
src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py
src/hyperion/utils/validation.py
tests/conftest.py
tests/unit_tests/experiment_plans/conftest.py
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_oav_snapshot_plan.py
tests/unit_tests/experiment_plans/test_pin_tip_centring.py
tests/unit_tests/experiment_plans/test_rotation_scan_plan.py
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py
tests/unit_tests/external_interaction/callbacks/conftest.py

Fixes DiamondLightSource/dodal#601
Link to dodal PR (if required): DiamondLightSource/dodal#656
1. Tests pass
2. Plans continue operating

Dodal 601 convert smargon to ophyd async

---

utility_scripts/build_imginfo.sh
utility_scripts/run_imginfo.sh

These changes to the utility scripts assist in the building of the debug version of `imginfo` in the docker container image and launching of the built image in interactive mode for debugging.
Fixes #N/A
Link to imginfo PR (if required): githubgphl/imginfo#4

Enhancements to build_imginfo.sh and run_imginfo.sh to enable building of the debug dockerfile and convenient launching

---

src/hyperion/device_setup_plans/read_hardware_for_setup.py
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
src/hyperion/experiment_plans/rotation_scan_plan.py
src/hyperion/external_interaction/callbacks/ispyb_callback_base.py
src/hyperion/external_interaction/callbacks/rotation/nexus_callback.py
src/hyperion/external_interaction/callbacks/xray_centre/nexus_callback.py
src/hyperion/parameters/constants.py
src/hyperion/utils/validation.py
tests/system_tests/experiment_plans/test_fgs_plan.py
tests/system_tests/experiment_plans/test_plan_system.py
tests/system_tests/external_interaction/test_nexgen.py
tests/unit_tests/experiment_plans/conftest.py
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_rotation_scan_plan.py
tests/unit_tests/external_interaction/callbacks/conftest.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
tests/unit_tests/external_interaction/callbacks/xray_centre/test_nexus_handler.py
tests/unit_tests/external_interaction/test_write_rotation_nexus.py

Fixes #1482 
- Combines "read hardware for nexus" into the reading during the plan
- Removes "ispyb" from plan stub names, to make them just "read pre/during collection"
1. Run tests

Combine nexus and ispyb hardware readings and improve naming

---

.github/workflows/test_data/setup.cfg
.github/workflows/test_data/setup.cfg.pinned
.github/workflows/test_data/setup.cfg.unpinned
setup.cfg

Fixes #1489
1. See nothing broke

remove unused dependencies and pins

---

setup.cfg
tests/unit_tests/experiment_plans/test_grid_detection_plan.py

Fixes DiamondLightSource/dodal#655
Link to dodal PR (if required): DiamondLightSource/dodal#675
1. Tests still pass

Revert unit test fix relating to now-reverted dodal thumbnail generation

---

src/hyperion/device_setup_plans/manipulate_sample.py
src/hyperion/experiment_plans/oav_snapshot_plan.py
src/hyperion/experiment_plans/rotation_scan_plan.py
src/hyperion/parameters/components.py
src/hyperion/utils/validation.py
tests/conftest.py
tests/system_tests/external_interaction/test_ispyb_dev_connection.py
tests/test_data/parameter_json_files/good_test_rotation_scan_parameters.json
tests/unit_tests/conftest.py
tests/unit_tests/experiment_plans/test_oav_snapshot_plan.py
tests/unit_tests/experiment_plans/test_rotation_scan_plan.py

Addresses the remaining parts of #349 
1. When supplied with `snapshot_omegas_deg` as an array of up to 4 snapshot angles, and  `snapshot_directory` in the request parameters to a rotation scan, OAV  snapshots will be acquired prior to the rotation scan at the requested angles and deposited in ispyb
2. If `snapshot_omegas_deg` is empty or missing, no snapshots will be acquired and snapshot filenames will be registered in ispyb as specified by the `ispyb_extras.xtal_snapshots_omega_start` array

349 rotation scan now collects OAV snapshots

---

setup.cfg
src/hyperion/device_setup_plans/setup_panda.py
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
tests/unit_tests/device_setup_plans/test_setup_panda.py

Fixes the directory provider update method being made asynchronous for dodal type checking
Link to dodal PR (if required): [#719](https://github.com/DiamondLightSource/dodal/pull/719), [#718](https://github.com/DiamondLightSource/dodal/pull/718)
1. Confirm that PandA writes to correct directory
2. Confirm that setting output directory is blocking

Wrap async behaviour of updating directory_provider

---

src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py
src/hyperion/experiment_plans/pin_centre_then_xray_centre_plan.py
tests/system_tests/external_interaction/test_ispyb_dev_connection.py
tests/unit_tests/conftest.py
tests/unit_tests/experiment_plans/test_grid_detect_then_xray_centre_plan.py
tests/unit_tests/experiment_plans/test_pin_centre_then_xray_centre_plan.py
tests/unit_tests/external_interaction/callbacks/conftest.py

Fixes #824
Link to dodal PR (if required): N/A
1. ispyb comments should now appear when the pin tip is too short or too long
2. Tests pass

(#842) Fix ispyb activation so that messages can be logged from pin tip detection

---

setup.cfg

Unpins the dodal dependency in setup.cfg so that it pulls from main rather than a PR commit hash

Unpin dodal before release

---

setup.cfg
src/hyperion/device_setup_plans/setup_panda.py
src/hyperion/experiment_plans/flyscan_xray_centre_plan.py
tests/unit_tests/device_setup_plans/test_setup_panda.py
tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py

Fixes #1517
Link to dodal PR (if required): DiamondLightSource/dodal#742
* The pulse block output pulse width should now be the same as the exposure time
* The pcap file name should now be unique (appended with the current timestamp)
* The extra 'panda' subdirectory should no longer be created
* Tests should still pass

1517 fix panda issues discovered during testing

---

setup.cfg
src/hyperion/external_interaction/config_server.py
src/hyperion/parameters/constants.py

use daq config service from pypi

---

tests/conftest.py
tests/system_tests/experiment_plans/test_fgs_plan.py
tests/unit_tests/experiment_plans/conftest.py
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py

Remove a few references to ophyd. Most of what's left should be those needed for devices that are still ophyd or `NullStatus`, which will need to think of a clean replacement for

Removed some references to ophyd

---

src/hyperion/experiment_plans/robot_load_then_centre_plan.py
tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py

Part of https://github.com/DiamondLightSource/hyperion/issues/1514

Do not move lower gonio until the robot is safely away

---

.vscode/hyperion-mx-bluesky.code-workspace
setup.cfg
src/hyperion/experiment_plans/oav_snapshot_plan.py
src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py
src/hyperion/parameters/components.py
src/hyperion/parameters/gridscan.py
src/hyperion/parameters/rotation.py
tests/system_tests/external_interaction/test_ispyb_dev_connection.py
tests/unit_tests/experiment_plans/test_oav_snapshot_plan.py
tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
tests/unit_tests/parameters/test_parameter_model.py

For https://github.com/DiamondLightSource/mx-bluesky/issues/162
Moves the parameted model base components to mx-bluesky, re-adds the default values here in hyperion
Link to MXB PR (if required): #[163](https://github.com/DiamondLightSource/mx-bluesky/pull/163)
1. Run tests

Move the basic parameter model components to MXB
