.pre-commit-config.yaml, Pipfile, Pipfile.lock, README.md
Runs 
```
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
Check for image files................................(no files to check)Skipped
Check python ast.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for added large files..............................................Passed
Don't commit to 'main'...................................................Passed
```
=> Add pre-commit hooks

src/artemis/devices/eiger.py, src/artemis/devices/eiger_odin.py, src/artemis/devices/system_tests/test_eiger_system.py
=> Fixes #18 add wait for meta filewriter to be ready

src/artemis/devices/eiger_odin.py, src/artemis/devices/unit_tests/test_odin.py
Fixes #12
Also added extra unit test for the odin
=> added more comprehensive error message for node error check

Pipfile, Pipfile.lock, README.md, src/artemis/devices/det_dim_constants.py, src/artemis/devices/eiger.py, src/artemis/devices/fast_grid_scan.py, src/artemis/fast_grid_scan_plan.py, src/artemis/main.py, src/artemis/system_tests/test_main_system.py, src/artemis/tests/test_fast_grid_scan_plan.py, src/artemis/tests/test_main_system.py
See https://jira.diamond.ac.uk/browse/MXGDA-3764
To test:
* Update dependencies
* Run modified tests and confirm they pass
* Start up a runner as in README instructions and start/stop some scans
* Confirm runner acts as expected and starts a scan based on the ophyd/bluesky logs in /tmp/
=> Mxgda 3764: Run plan from flask server

src/artemis/main.py
=> 33: Set a hostname to be externally visible for testing

src/artemis/devices/eiger.py, src/artemis/devices/eiger_odin.py
=> add put for the meta filename back in

src/artemis/devices/Detector.py, src/artemis/devices/det_dist_to_beam_converter.py, src/artemis/devices/eiger.py, src/artemis/devices/eiger_odin.py, src/artemis/devices/status.py, src/artemis/devices/unit_tests/test_beam_converter.py, src/artemis/devices/unit_tests/test_eiger.py, src/artemis/devices/unit_tests/test_zebra.py, src/artemis/fast_grid_scan_plan.py, src/artemis/ispyb/ispyb_dataclass.py, src/artemis/ispyb/store_in_ispyb.py, src/artemis/ispyb/tests/test_store_in_ispyb.py, src/artemis/tests/test_fast_grid_scan_plan.py
=> 55: Run black on codebase to format

src/artemis/devices/eiger.py, src/artemis/devices/fast_grid_scan.py, src/artemis/devices/system_tests/test_eiger_system.py, src/artemis/devices/unit_tests/test_eiger.py, src/artemis/fast_grid_scan_plan.py, src/artemis/tests/test_fast_grid_scan_plan.py
Fixes #50
To test:
* Confirm new test passes and detector parameters now correctly passed to eiger
=> 50: Fixed passing detector parameters to eiger

src/artemis/fast_grid_scan_plan.py, src/artemis/ispyb/store_in_ispyb.py
Fixes #65 
Apologies for the import fixes, not sure why they weren't already in the codebase
To test:
* Run unit tests and confirm they pass
=> 65: Put artemis in ISPyB comments

codecov.yml
=> 76: Added lenient codecov

src/artemis/devices/fast_grid_scan.py, src/artemis/devices/unit_tests/test_gridscan.py
Fixes #34
To test:
* Confirm unit tests still pass
=> 34 grid scan complete fails

src/artemis/devices/detector.py, src/artemis/devices/eiger.py, src/artemis/nexus_writing/write_nexus.py
Fixes #59 
To test:
* Confirm unit tests still pass
=> 59: Set nexus pixels correctly based on ROI

src/artemis/fast_grid_scan_plan.py, src/artemis/ispyb/store_in_ispyb.py, src/artemis/ispyb/tests/test_store_in_ispyb.py
=> 64: Call zocalo and ISPyB as part of the plan

Pipfile, Pipfile.lock
To test:
* Confirm tests now pass
=> Updated ophyd to master

src/artemis/devices/fast_grid_scan.py, src/artemis/devices/unit_tests/test_gridscan.py, src/artemis/nexus_writing/write_nexus.py, src/artemis/parameters.py
Fixes #30 
To test:
* Confirm unit tests run
* Confirm this code has the additional fast grid scan settings from https://github.com/DiamondLightSource/python-artemis/tree/testing_round_5
=> 30: 3d grid scans

Pipfile, Pipfile.lock
=> #136 Add matplotlib to pipfile

contributing.md
=> #122: Created contributing file

src/artemis/fast_grid_scan_plan.py, src/artemis/tests/test_zocalo_interaction.py, src/artemis/zocalo_interaction.py
Fixes #97 
To test:
* Confirm unit tests pass
=> 97: Added function to wait for analysis results

contributing.md
Add instruction to delete merged branches.
=> Minor addition to contributing file

src/artemis/nexus_writing/write_nexus.py
=> #116: Change sam_{x,y,z} units to um

src/artemis/devices/slit_gaps.py, src/artemis/fast_grid_scan_plan.py, src/artemis/ispyb/ispyb_dataclass.py, src/artemis/tests/test_fast_grid_scan_plan.py
=> 140 slit gaps using ophyd

.github/workflows/code.yml, Pipfile, Pipfile.lock, README.md
Fixes #152
To test:
* Reinstall and confirm unit tests still pass
=> Upgraded python version

src/artemis/nexus_writing/tests/test_write_nexus.py, src/artemis/parameters.py, src/artemis/tests/test_parameters.py
Fixes #169
To test:
* Confirm all unit tests are passing
=> (#169) Ensure new instances of FullParameters are copies

Pipfile, Pipfile.lock, pyproject.toml, setup.cfg
=> #181: Change setup to package format

Pipfile, README.md, run_artemis.sh, setup.py, src/artemis/__main__.py, src/artemis/tests/test_main_system.py
This adds a minimal `setup.py`, required by some versions of setuptools for an editable install of our package. It also introduces a change in how the bluesky runner is started.
=> Fix build system

src/artemis/tests/test_zocalo_interaction.py, src/artemis/zocalo_interaction.py
Fixes #188 
To test:
Make sure tests still pass
=> reverse zocalo coordinates and use centre_of_mass rather than max_voxel

src/artemis/devices/unit_tests/test_eiger.py
=> #94: Add tests for eiger.py

src/artemis/nexus_writing/tests/test_write_nexus.py
=> 174 merge nexus test fixtures

src/artemis/devices/detector.py, src/artemis/devices/unit_tests/test_detector.py
=> 206: Ensure directory from GDA is correct

src/artemis/nexus_writing/write_nexus.py
=> Change Underload to zero in nexus file

src/artemis/devices/detector.py, src/artemis/parameters.py, test_parameters.json
Fixes #29 
@bentom08 I think this is sufficient on the Artemis end, but may you check to ensure I've not missed anything?
Also before the merge we need to make a change to GDA to pass the path. @DominicOram
=> 29 filepath for lookuptable

src/artemis/devices/system_tests/test_undulator_system.py
=> #146: Test that undulator can connect to simulation

src/artemis/fast_grid_scan_plan.py, src/artemis/ispyb/store_in_ispyb.py, src/artemis/ispyb/tests/test_store_in_ispyb.py, src/artemis/tests/test_fast_grid_scan_plan.py
=> #77: Inform ISpyB if scan fails

src/artemis/log.py, src/artemis/tests/test_log.py
=> Fix existing folder check in logging

.vscode/launch.json
Fixes #267 
To test:
* Add a breakpoint on a test and run in debug
* Confirm breakpoint gets hit
=> (#267) Fix debug unit test launch (doesn't play nice with cov)

src/artemis/fast_grid_scan_plan.py
Fixes #237 
To test:
* Confirm similar change made on live code (`/dls_sw/i03/software/artemis`)
* Confirm unit tests pass
=> (#237) Do not move omega

.gitignore, .vscode/launch.json, src/artemis/devices/oav/utils.py, src/artemis/devices/unit_tests/test_oav.py, src/artemis/ispyb/ispyb_dataclass.py, src/artemis/ispyb/store_in_ispyb.py, src/artemis/ispyb/tests/test_store_in_ispyb.py, src/artemis/parameters.py
Fixes #240 from the artemis side by composing the comment in store_in_ispyb
=> 240 ispyb comment

src/artemis/fast_grid_scan_plan.py
Setting it at the end of the plan instead. Fixes #114
=> 114 set no steps to 0 at beginning of scan

src/artemis/devices/eiger_odin.py, src/artemis/devices/system_tests/test_eiger_system.py
System tests running with these changes
=> 225 fix system tests

.github/workflows/code.yml, src/artemis/fast_grid_scan_plan.py
Fixes #238 
Note that I've just started the omega move regardless, I'm doing it asynchronously so don't think it will cause any slow down.
=> (#238) Move to omega 0 at start of plan

src/artemis/devices/eiger.py
Fixes #275 
To test:
* Confirm resolution on the ticket sounds sensible and below does as suggested
=> #275: Disable ROI after checking successful data collection

src/artemis/devices/fast_grid_scan.py, src/artemis/devices/unit_tests/test_gridscan.py
Fixes #235 
To test:
* Confirm new unit test fails on main but passes on this branch
=> (#235) Implement flyable properly

.github/workflows/assigned_issues_to_in_progress.yml, .github/workflows/get_issue_from_pr.yml, .github/workflows/get_project_data.yml, .github/workflows/open_prs_to_review.yml, .github/workflows/opened_issues_to_backlog.yml, .github/workflows/rework_prs_to_in_progress.yml
Fixes #87 
1. See https://github.com/DiamondLightSource/python-artemis/issues/87#issuecomment-1302731823
=> 87: Automate dev workflows using GH actions

src/artemis/devices/eiger.py, src/artemis/devices/unit_tests/test_eiger.py
Fixes #241
1. Confirm unit tests still pass
2. Confirm new unit test passes - I'm not overly happy with the test as it will probably pass on main too but it describes the real behaviour of the device as documented in #241
=> 241: Fixes race condition on stale params

src/artemis/fgs_communicator.py, src/artemis/tests/test_fast_grid_scan_plan.py, src/artemis/tests/test_fgs_communicator.py, src/artemis/zocalo_interaction.py
Fixes #231
1. Check this change functionally achieves the same thing as the fix on live
2. Confirm tests adjusted correctly and still passing
=> #231 Adjust results from Zocalo

.vscode/settings.json
=> (#361) updating default python interpreter

src/artemis/devices/oav/oav_centring.py, src/artemis/devices/oav/oav_detector.py
Fixes #411
1. check imports/tests resolve correctly
=> fix old import in oav centring

src/artemis/external_interaction/communicator_callbacks.py
=> remove unused import

run_artemis.sh
Fixes #389
1. Run `./run_artemis.sh -b=i03` and confirm you get an error about not being on the right machine
2. Confirm `run_artemis.sh` contains changes from https://github.com/DiamondLightSource/python-artemis/pull/418/files
=> (#389) run_artemis will now fail if not run as the correct user

src/artemis/__main__.py, src/artemis/devices/eiger.py, src/artemis/fast_grid_scan_plan.py
Moves device creation earlier to hopefully fix the issue we've had with devices not getting connected
=> DO NOT MERGE TO MAIN: A hacky fix to moving device creation earlier

src/artemis/fast_grid_scan_plan.py, src/artemis/system_tests/test_fgs_plan.py
Fixes #460
1. Run steps on linked issue and confirm there is no longer an error
2. Confirm modified test fails on main and passes here
=> 460 fix finalize

src/artemis/external_interaction/callbacks/fgs/tests/test_zocalo_handler.py, src/artemis/external_interaction/callbacks/fgs/zocalo_callback.py, src/artemis/fast_grid_scan_plan.py
Fixes #439 
Does not include ispyb interaction, see #487 for this,
=> 439: No diffraction

src/artemis/__main__.py, src/artemis/devices/eiger.py, src/artemis/devices/unit_tests/test_eiger.py, src/artemis/experiment_plans/experiment_registry.py, src/artemis/experiment_plans/fast_grid_scan_plan.py, src/artemis/external_interaction/callbacks/fgs/tests/test_fgs_callback_collection.py, src/artemis/parameters.py, src/artemis/system_tests/test_fgs_plan.py, src/artemis/system_tests/test_main_system.py, src/artemis/unit_tests/test_fast_grid_scan_plan.py
Is a quick hotfix that will solve the underlying issue causing #451 but not a proper solution.
@dperl-dls and @noemifrisina, thoughts on this as a quick solution for Thursday? I think it's pretty messy and I suspect the tests need fixing too.
=> #451 Creating devices before running plans

src/artemis/devices/fast_grid_scan.py, src/artemis/devices/system_tests/test_gridscan_system.py, src/artemis/experiment_plans/fast_grid_scan_plan.py
Fixes #438
1. Run the new `test_given_valid_params_when_kickoff_then_completion_status_increases_and_finishes` against main and confirm it fails
2. Confirm it passes on this branch
=> 438: Reset FGS position counter on start up

src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py, src/artemis/external_interaction/zocalo/zocalo_interaction.py
Fixes #503
1. Confirm new test passes
=> (#503) Exceptions inside receive_results are now re-raised

fake_zocalo/__main__.py, src/artemis/external_interaction/callbacks/fgs/tests/test_zocalo_handler.py, src/artemis/external_interaction/callbacks/fgs/zocalo_callback.py, src/artemis/external_interaction/system_tests/test_zocalo_system.py, src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py, src/artemis/external_interaction/zocalo/zocalo_interaction.py
Fixes #501
1. Confirm tests pass (including system test)
=> 501 zocalo empty list

src/artemis/system_tests/test_fgs_plan.py
Fixes #507
1. Run tests in test_fgs_plan.py (specifically test_full_plan_tidies_at_end and test_full_plan_tidies_at_end_when_plan_fails)
=> fix test eiger init and test patching

codecov.yml, setup.cfg, src/artemis/external_interaction/callbacks/fgs/zocalo_callback.py, src/artemis/external_interaction/system_tests/conftest.py, src/artemis/external_interaction/system_tests/test_ispyb_dev_connection.py, src/artemis/external_interaction/system_tests/test_zocalo_system.py, src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py, src/artemis/external_interaction/zocalo/zocalo_interaction.py, src/artemis/system_tests/test_fgs_plan.py
Fixes #510 
to test: run new test
=> Restore writing the analysis time to comments

fake_zocalo/__main__.py, src/artemis/external_interaction/callbacks/fgs/zocalo_callback.py, src/artemis/external_interaction/system_tests/test_zocalo_system.py, src/artemis/external_interaction/unit_tests/test_write_nexus.py, src/artemis/system_tests/test_fgs_plan.py
Fixes #487
1. Wait for #511  to be merged
2. Remove skip mark and run test
=> Improve logging to ispyb when there is no diffraction

fake_zocalo/__main__.py, src/artemis/devices/aperture.py, src/artemis/devices/aperturescatterguard.py, src/artemis/devices/fast_grid_scan_composite.py, src/artemis/devices/scatterguard.py, src/artemis/experiment_plans/fast_grid_scan_plan.py, src/artemis/external_interaction/callbacks/fgs/tests/test_zocalo_handler.py, src/artemis/external_interaction/callbacks/fgs/zocalo_callback.py, src/artemis/external_interaction/system_tests/conftest.py, src/artemis/external_interaction/system_tests/test_zocalo_system.py, src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py, src/artemis/external_interaction/zocalo/zocalo_interaction.py, src/artemis/parameters.py, src/artemis/system_tests/test_fgs_plan.py, src/artemis/unit_tests/test_fast_grid_scan_plan.py
=> 486 choose aperture based on xtal size

.pre-commit-config.yaml
Update isort 
1. Check that all pre-commits run fine
=> Bump isort version

src/artemis/devices/aperturescatterguard.py
Adds link to some docs
1. Confirm docs are ok
2. Confirm link works
=> Added link to collision docs in code

.github/workflows/assigned_issues_to_in_progress.yml, .github/workflows/get_issue_from_pr.yml, .github/workflows/get_project_data_and_move_column.yml, .github/workflows/open_prs_to_review.yml, .github/workflows/opened_issues_to_backlog.yml, .github/workflows/rework_prs_to_in_progress.yml
Fixes #530
1. Confirm actions are still working and linked docs are reasonable
=> 530 Adds some docs around github actions

src/artemis/unit_tests/test_fast_grid_scan_plan.py
Fixes #536 
1. Run test and confirm it passes
2. Confirm if you revert https://github.com/DiamondLightSource/python-artemis/pull/537/commits/44b515782fa4431df6ed2f881982ff73daa8c870
=> Add a test to confirm order of zocalo end call vs disarming detector

src/artemis/experiment_plans/experiment_registry.py, src/artemis/external_interaction/callbacks/fgs/zocalo_callback.py, src/artemis/external_interaction/system_tests/test_zocalo_system.py, src/artemis/parameters/external_parameters.py, src/artemis/parameters/internal_parameters.py, src/artemis/parameters/tests/test_internal_parameters.py, src/artemis/system_tests/test_main_system.py
=> Collection of minor issues found from testing v2.0.0

dls_dev_env.sh
1. Run `dls_dev_env.sh`
2. Ensure local dodal is used
=> Force us to use a local version of dodal in dev

deploy/deploy_artemis.py, deploy/deploy_artemis.sh, deploy_artemis.py, setup.cfg
Fixes #314
1. Follow instructions at https://github.com/DiamondLightSource/python-artemis/wiki/Creating-a-release-and-deploying-it#deploying-a-release to test a release locally
2. Confirm a full deployment happens as expected
=> 314: Added basic deploy script

src/artemis/external_interaction/ispyb/ispyb_dataclass.py, src/artemis/external_interaction/ispyb/store_in_ispyb.py, src/artemis/external_interaction/system_tests/conftest.py, src/artemis/external_interaction/unit_tests/test_store_in_ispyb.py, src/artemis/parameters/external_parameters.py, src/artemis/parameters/schemas/ispyb_parameters_schema.json, src/artemis/parameters/tests/test_data/bad_test_parameters_wrong_version.json, src/artemis/parameters/tests/test_data/good_test_parameters.json, src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters.json, test_parameters.json
Fixes #571
1. Run the automated unit tests and ensure they still work
=> (#571) Update pixels_per_micron to microns_per_pixel

setup.cfg, src/artemis/experiment_plans/tests/test_experiment_registry.py, src/artemis/parameters/internal_parameters.py
Fixes #570 
Ended up becoming a small params change, adding a base class to make sure num_images is always available, and adding it to the two experiment param base classes
Link to dodal PR (if required): [#26](https://github.com/DiamondLightSource/dodal/pull/26)
1. Run tests
=> 570 fix type hints and params

README.md, run_artemis.sh, src/artemis/__main__.py, src/artemis/system_tests/test_main_system.py
Fixes #600
1. Run new unit tests in test_main_system.py
2. Confirm artemis doesn't automatically connect to hardwere when running with the flag --skip_startup_connection, and that it does without this flag
=> Adds flag to skip startup connection scripts

src/artemis/system_tests/test_aperturescatterguard_system.py, src/artemis/system_tests/test_device_setups_and_cleanups.py
=> remove aperturescatterguard system test

setup.cfg, src/artemis/parameters/internal_parameters/plan_specific/rotation_scan_internal_params.py, src/artemis/parameters/internal_parameters/plan_specific/tests/test_rotation_internal_parameters.py, src/artemis/parameters/tests/test_internal_parameters.py
Fixes https://github.com/DiamondLightSource/dodal/issues/45
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/46
=> Remove Unused EigerTriggerNumber

setup.cfg, src/artemis/parameters/internal_parameters/plan_specific/tests/test_fgs_internal_parameters.py
Fixes #630 
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/47
1. Confirm tests pass with updates from above
=> Fix issue with zocalo errors on v4.0.0

setup.cfg, src/artemis/external_interaction/callbacks/fgs/tests/test_ispyb_handler.py, src/artemis/log.py, src/artemis/unit_tests/test_log.py
Fixes #569
Link to dodal PR (if required): (https://github.com/DiamondLightSource/dodal/pull/38)
1. Confirm unit tests pass and are sensible
=> Move more logging into dodal

setup.cfg, src/artemis/parameters/internal_parameters/plan_specific/fgs_internal_params.py, src/artemis/unit_tests/test_fast_grid_scan_plan.py
Fixes #560
Link to dodal PR (if required): #https://github.com/DiamondLightSource/dodal/pull/48
Requires the following to be merged first:
* https://github.com/DiamondLightSource/python-artemis/pull/640
* https://github.com/DiamondLightSource/python-artemis/pull/639
=> Run the eiger without setting number of triggers

setup.cfg, src/artemis/experiment_plans/full_grid_scan.py
Fixes #653
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/64
1. Confirm existing unit tests pass
=> Use xray centring OAV params when doing an xray centre

setup.cfg
Unpin `nexgen` and use latest version
=> Unpin nexgen 

src/artemis/experiment_plans/experiment_registry.py, src/artemis/experiment_plans/full_grid_scan.py, src/artemis/experiment_plans/oav_grid_detection_plan.py, src/artemis/experiment_plans/tests/test_grid_detection_plan.py, src/artemis/external_interaction/ispyb/ispyb_dataclass.py, src/artemis/parameters/internal_parameters/internal_parameters.py, src/artemis/parameters/internal_parameters/plan_specific/fgs_internal_params.py, src/artemis/parameters/internal_parameters/plan_specific/grid_scan_with_edge_detect_params.py, src/artemis/parameters/internal_parameters/plan_specific/rotation_scan_internal_params.py, src/artemis/parameters/schemas/experiment_schemas/grid_scan_with_edge_detect_params_schema.json, src/artemis/parameters/schemas/full_external_parameters_schema.json, src/artemis/parameters/schemas/ispyb_parameters_schema.json, src/artemis/parameters/tests/test_data/good_test_parameters.json, src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters.json, test_parameter_defaults.json, test_parameters.json
Fixes #652, fixes #670, fixes #373, fixes #658
This has been tested on the beamline and works sufficiently, it could use some tidying though. See #671, #672, #673, #674. Please review bearing these in mind
1. Tests pass
=> Do grid detection in Artemis

src/artemis/__main__.py, src/artemis/experiment_plans/experiment_registry.py, src/artemis/external_interaction/callbacks/abstract_plan_callback_collection.py, src/artemis/external_interaction/callbacks/fgs/fgs_callback_collection.py, src/artemis/system_tests/test_main_system.py, src/artemis/unit_tests/test_log.py
Fixes #668
1. Confirm tests pass, including new test
2. Confirm this is compatible with the work done in https://github.com/DiamondLightSource/python-artemis/pull/621
=> Created a more generic callback structure to more easily allow different plans

src/artemis/parameters/tests/test_external_parameters.py
=> Fix accidentally broken unit test

src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py
Fixes #689
1. Confirm new test passes and tests what it says it tests
=> Add test for disarming detector on failed grid scan

setup.cfg, src/artemis/experiment_plans/oav_grid_detection_plan.py, src/artemis/experiment_plans/tests/test_grid_detection_plan.py
Fixes #699
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/88
1. Confirm modified unit tests pass and code is cleaner
=> Improve the use of the pin tip detect device

setup.cfg, src/artemis/external_interaction/ispyb/store_in_ispyb.py, src/artemis/external_interaction/system_tests/conftest.py
Fixes #705
To test: run ispyb system tests
=> Fix ispyb deposition bug

setup.cfg
Needed to temporarily fix artemis - issue to resolve this in #713
=> roll back bluesky

setup.cfg
1. Confirm the unit tests run in CI
=> Add dodal back in

src/artemis/external_interaction/system_tests/test_zocalo_system.py, src/artemis/system_tests/test_fgs_plan.py
Fixes a few broken system tests
1. Check that all system tests run
=> Fix failing system tests

setup.cfg, src/artemis/device_setup_plans/setup_zebra.py, src/artemis/device_setup_plans/unit_tests/test_zebra_setup.py, src/artemis/experiment_plans/tests/test_rotation_scan_plan.py
Fixes #749
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/100
=> Tidy up arm/disarm zebra

setup.cfg, src/artemis/device_setup_plans/setup_zebra.py, src/artemis/experiment_plans/optimise_attenuation_plan.py, src/artemis/experiment_plans/tests/test_optimise_attenuation_plan.py
Fixes #701 
This requires https://github.com/DiamondLightSource/dodal/pull/90 and https://github.com/DiamondLightSource/dodal/pull/94 to first be merged
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/105
1. Check unit test is reasonable
2. Confirm logic is the same as in the GDA's mx-config/scripts/attenuation_optimiser function run_xspress3mini_optimisation_routine()
=> Add total count optimise attenuation

setup.cfg, src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py
Fixes #767
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/107
=> Fix centre being one box out

src/artemis/experiment_plans/fast_grid_scan_plan.py, src/artemis/experiment_plans/tests/conftest.py, src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py
Fixes #686
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/116, not required exactly but replaces the logging done Artemis side
=> Fast grid scan without grid detect arms detector

src/artemis/device_setup_plans/setup_oav.py, src/artemis/experiment_plans/oav_grid_detection_plan.py
Fixes #798
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/118
=> Add more debugging around finding the pin tip

run_artemis.sh
=> Increase timeout when restarting artemis

setup.cfg, src/artemis/experiment_plans/optimise_attenuation_plan.py, src/artemis/experiment_plans/tests/test_optimise_attenuation_plan.py
Fixes #779 
Link to dodal PR (if required): [#114](https://github.com/DiamondLightSource/dodal/pull/114)
1. Check issue requirements are all addressed
2. Confirm new tests run and are sensible
=> 779 fix fluo optimise

src/artemis/device_setup_plans/setup_oav.py, src/artemis/device_setup_plans/unit_tests/test_setup_oav.py
Fixes #820
1. Confirm test passes
=> Control zoom and flatfield correctly in tip/grid detect

src/artemis/external_interaction/unit_tests/test_store_in_ispyb.py, src/artemis/external_interaction/unit_tests/test_zocalo_interaction.py
1. Confirm linter happy and tests pass
=> Fix linting issues

src/artemis/device_setup_plans/setup_oav.py, src/artemis/device_setup_plans/unit_tests/test_setup_oav.py
Fixes #830
Mainly fixed by dodal change but this is also important
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/131
1. Confirm tests pass on this branch and fail on main
=> Fixes issue with OAV setup occassionally hanging

setup.cfg, src/artemis/device_setup_plans/setup_oav.py, src/artemis/device_setup_plans/unit_tests/test_setup_oav.py, src/artemis/experiment_plans/oav_grid_detection_plan.py, src/artemis/experiment_plans/pin_tip_centring_plan.py, src/artemis/experiment_plans/tests/conftest.py, src/artemis/experiment_plans/tests/test_pin_tip_centring.py
Part of #499 but not full fix.
=> Add a pin tip centring algorithm 

src/artemis/experiment_plans/full_grid_scan.py, src/artemis/experiment_plans/tests/test_fast_grid_scan_plan.py, src/artemis/experiment_plans/tests/test_full_grid_scan_plan.py, src/artemis/external_interaction/callbacks/ispyb_callback_base.py, src/artemis/external_interaction/ispyb/ispyb_dataclass.py, src/artemis/external_interaction/ispyb/store_in_ispyb.py, src/artemis/external_interaction/nexus/nexus_utils.py, src/artemis/external_interaction/system_tests/test_write_rotation_nexus.py, src/artemis/external_interaction/unit_tests/conftest.py, src/artemis/external_interaction/unit_tests/test_ispyb_dataclass.py, src/artemis/external_interaction/unit_tests/test_store_in_ispyb.py, src/artemis/parameters/schemas/full_external_parameters_schema.json, src/artemis/parameters/schemas/ispyb_parameters_schema.json, src/artemis/parameters/tests/test_data/artemis_parameters.json, src/artemis/parameters/tests/test_data/bad_test_parameters_wrong_version.json, src/artemis/parameters/tests/test_data/good_test_grid_with_edge_detect_parameters.json, src/artemis/parameters/tests/test_data/good_test_parameters.json, src/artemis/parameters/tests/test_data/good_test_rotation_scan_parameters.json, test_parameter_defaults.json, test_parameters.json
Fixes #835
Review GDA too https://gerrit.diamond.ac.uk/c/gda/gda-mx/+/39641
Also see https://github.com/DiamondLightSource/dodal/pull/133
1. Run tests
1. Confirm GDA calls Artemis correctly still using the above gerrit change see instructions [here](https://github.com/DiamondLightSource/python-artemis/wiki/Running-a-Dummy-Mode-GDA-against-Artemis)
=> Fix issue with transmission being set incorrectly

.vscode/settings.json
1. Start vscode with the settings in the repo
2. Confirm it has stricter typing
Note:
As discussed, we won't fix all the issues now but will fix them as we go
=> Added stricter typing to vscode

setup.cfg, src/hyperion/device_setup_plans/manipulate_sample.py, src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py, src/hyperion/experiment_plans/tests/test_grid_detection_plan.py, src/hyperion/parameters/plan_specific/rotation_scan_internal_params.py, src/hyperion/parameters/plan_specific/stepped_grid_scan_internal_params.py, src/hyperion/snapshot_plan.py
Link to dodal PR (if required): [#151](https://github.com/DiamondLightSource/dodal/pull/158)
1. Check tests still pass
=> Backlight switches off when moved out

src/hyperion/__main__.py, src/hyperion/experiment_plans/__init__.py, src/hyperion/system_tests/test_main_system.py
Fixes #875
1. Confirm modified test passes
=> Added pin_tip_centre_then_xray_centre to available plans

src/hyperion/external_interaction/zocalo/zocalo_interaction.py
=> Increase zocalo timeout

.vscode/settings.json, src/hyperion/device_setup_plans/unit_tests/test_setup_oav.py, src/hyperion/experiment_plans/tests/test_grid_detect_then_xray_centre_plan.py, src/hyperion/experiment_plans/tests/test_grid_detection_plan.py, src/hyperion/external_interaction/callbacks/oav_snapshot_callback.py
Fixes #902 
Created new `grid_param_cb = GridDetectionCallback(params, 0.004)` and subscribed the callback to the run engine in order for tests to pass.
1. Confirm (relevant) tests passes
=> 902  fake grid detection

src/hyperion/experiment_plans/oav_grid_detection_plan.py, src/hyperion/experiment_plans/pin_tip_centring_plan.py, src/hyperion/experiment_plans/tests/conftest.py, src/hyperion/experiment_plans/tests/test_pin_tip_centring.py, src/hyperion/parameters/constants.py
- move to the limit if normal nudge would take it over since into-view steps are large
- update tests with limits
Fixes #906
1. Run tests
=> #906 check limits during pin tip centring

src/hyperion/experiment_plans/tests/test_flyscan_xray_centre_plan.py
Fixes #913 
Made a dictionary `mock_subscription_dict` that is pulled from a constant and tidying that up.
1. Run Tests
=> 913 Created a single dictionary that is pulled from a constant

live_test_rotation_params.json, live_test_rotation_params_move_xyz.json, setup.cfg, src/hyperion/experiment_plans/tests/test_grid_detection_plan.py, src/hyperion/external_interaction/callbacks/grid_detection_callback.py, src/hyperion/parameters/plan_specific/stepped_grid_scan_internal_params.py, src/hyperion/parameters/schemas/experiment_schemas/grid_scan_params_schema.json, src/hyperion/parameters/schemas/full_external_parameters_schema.json, src/hyperion/parameters/tests/test_data/bad_test_parameters_wrong_version.json, src/hyperion/parameters/tests/test_data/good_test_grid_with_edge_detect_parameters.json, src/hyperion/parameters/tests/test_data/good_test_parameters.json, src/hyperion/parameters/tests/test_data/good_test_pin_centre_then_xray_centre_parameters.json, src/hyperion/parameters/tests/test_data/good_test_rotation_scan_parameters.json, src/hyperion/parameters/tests/test_data/good_test_rotation_scan_parameters_nomove.json, src/hyperion/parameters/tests/test_data/good_test_stepped_grid_scan_parameters.json, src/hyperion/parameters/tests/test_external_parameters.py, test_parameter_defaults.json, test_parameters.json
Fixes #940
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/213
=> Add units to dwell time

src/hyperion/parameters/plan_specific/stepped_grid_scan_internal_params.py, src/hyperion/parameters/tests/test_data/bad_test_parameters_wrong_version.json, src/hyperion/parameters/tests/test_data/good_test_parameters.json, src/hyperion/parameters/tests/test_data/good_test_stepped_grid_scan_parameters.json, src/hyperion/parameters/tests/test_external_parameters.py, test_parameter_defaults.json, test_parameters.json
Fixes #966
1. Confirm tests now pass
=> Fix unit tests with valid fgs dwell time

setup.cfg, src/hyperion/experiment_plans/flyscan_xray_centre_plan.py, src/hyperion/experiment_plans/tests/conftest.py, src/hyperion/experiment_plans/tests/test_flyscan_xray_centre_plan.py
Fixes #794
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/230
Note this is cherry-picked from https://github.com/DiamondLightSource/hyperion/pull/936
1. Confirm tests pass and make sense
=> Set stub offsets to center after an XRC

setup.cfg, src/hyperion/experiment_plans/tests/conftest.py, src/hyperion/experiment_plans/tests/test_rotation_scan_plan.py
Fixes #976 
To test:
run tests
=> 976 update blueapi

setup.cfg, src/hyperion/device_setup_plans/read_hardware_for_setup.py, src/hyperion/external_interaction/callbacks/ispyb_callback_base.py, tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_pin_tip_centring.py, tests/unit_tests/external_interaction/callbacks/xray_centre/conftest.py
=> Fix to code to work for latest dodal

src/hyperion/parameters/plan_specific/pin_centre_then_xray_centre_params.py
Fixes #1006 along with https://github.com/DiamondLightSource/dodal/pull/248
Instructions for reviewer:
Confirm this new address is correct
Run tests
=> Use correct oav_centring_file address

run_hyperion.sh, setup.cfg
Fixes #1028 by applying suggested hotfix. After this merge, we can unpin ophyd-async in dodal
Link to dodal PR (if required): (https://github.com/DiamondLightSource/dodal/pull/262)
=> Apply ophyd-async version hotfix

src/hyperion/device_setup_plans/read_hardware_for_setup.py, src/hyperion/device_setup_plans/xbpm_feedback.py, src/hyperion/experiment_plans/oav_grid_detection_plan.py, src/hyperion/experiment_plans/optimise_attenuation_plan.py, src/hyperion/external_interaction/callbacks/aperture_change_callback.py, tests/unit_tests/external_interaction/callbacks/xray_centre/test_nexus_handler.py, tests/unit_tests/external_interaction/test_write_nexus.py
Fixes a couple of minor typing issues
1. `pip install pyright`
2. On main `pyright .`
3. On this branch `pyright .`
4. Confirm there are less errors on this branch
5. Confirm tests still pass and there is little behavior change
=> Fixed a handful of typing issues

setup.cfg, src/hyperion/experiment_plans/wait_for_robot_load_then_centre.py, tests/unit_tests/experiment_plans/conftest.py, tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py
Fixes #984
Note that it doesn't do ispyb interaction, which is covered by https://github.com/DiamondLightSource/hyperion/issues/1017
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/263
=> Add plan to arm, wait for robot load, then centre

.github/workflows/code.yml, setup.cfg
Fixes #1042 
1. Merge this with another test branch which has errors in the diff and see the CI fail
See https://github.com/DiamondLightSource/hyperion/actions/runs/7208414314/job/19637292662
=> 1042 Run Pyright on diffs in CI

dls_dev_env.sh
Installs the pre-commit hooks
1. Run `pre-commit uninstall`
2. Run `.git/hooks/pre-commit` and confirm the pre-commit hooks aren't installed
3. Run `./dls_dev_env.sh`
4. Run `.git/hooks/pre-commit` and confirm the pre-commit hooks are installed
=> Install pre-commit hooks as part of the dev env script

setup.cfg
=> Correct zmq

run_hyperion.sh, setup.cfg, src/hyperion/__main__.py, src/hyperion/device_setup_plans/check_topup.py, src/hyperion/experiment_plans/experiment_registry.py, src/hyperion/experiment_plans/flyscan_xray_centre_plan.py, src/hyperion/external_interaction/callbacks/__main__.py, src/hyperion/external_interaction/callbacks/abstract_plan_callback_collection.py, src/hyperion/log.py, src/hyperion/parameters/cli.py, tests/unit_tests/external_interaction/callbacks/test_external_callbacks.py
Fixes #1100 
- Fixes the broken logging setup
- Instantiates gridscan callbacks for all plans where they are used, not just the xray centring plan
- Fixes typo in startup script
- adds a bunch more logging around FGS kickoff race condition https://github.com/DiamondLightSource/hyperion/issues/1101
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/309
1. Check tests haven't broken
=> v8.7 bugfixes from beamline testing

src/hyperion/experiment_plans/rotation_scan_plan.py, src/hyperion/external_interaction/callbacks/ispyb_callback_base.py, tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py
Fixes https://github.com/DiamondLightSource/hyperion/issues/1105
2. Confirm reading the test that the units being set/read make more sense
=> Fix energy off by 1000

setup.cfg, src/hyperion/experiment_plans/flyscan_xray_centre_plan.py, src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py
Fixes #1101 
Link to dodal PR (if required): [#317](https://github.com/DiamondLightSource/dodal/pull/317)
Has already been tested on the beamline.
1. See tests aren't failing.
=> #1101 Wait for moves before FGS kickoff

src/hyperion/device_setup_plans/setup_panda.py, src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py, src/hyperion/parameters/schemas/detector_parameters_schema.json, tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py
Fixes #1119 
1. Confirm all bullet points in issue are addressed
2. Tests pass
=> Panda hotfixes

src/hyperion/device_setup_plans/setup_zebra.py, tests/unit_tests/device_setup_plans/test_zebra_setup.py
Fixes #1117
This is quite a generic decorator and so maybe it makes sense in `dodal` but I really don't like that we have to do this so I would rather not encourage it elsewhere. Happy to be argued with though
1. Confirm new tests are good and pass
=> Retry writing to the zebra if it fails

.pre-commit-config.yaml, src/hyperion/device_setup_plans/manipulate_sample.py, src/hyperion/device_setup_plans/setup_panda.py, src/hyperion/experiment_plans/__init__.py, src/hyperion/experiment_plans/experiment_registry.py, src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py, src/hyperion/experiment_plans/rotation_scan_plan.py, src/hyperion/experiment_plans/set_energy_plan.py, src/hyperion/external_interaction/callbacks/__init__.py, src/hyperion/external_interaction/callbacks/abstract_plan_callback_collection.py, src/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py, src/hyperion/external_interaction/ispyb/ispyb_dataclass.py, src/hyperion/external_interaction/ispyb/store_datacollection_in_ispyb.py, src/hyperion/external_interaction/nexus/write_nexus.py, src/hyperion/parameters/internal_parameters.py, tests/unit_tests/external_interaction/callbacks/test_plan_reactive_callback.py, tests/unit_tests/external_interaction/test_store_datacollection_in_ispyb.py, tests/unit_tests/hyperion/test_main_system.py
Fixes #1130
All developers will also need to re-run `./dls_dev_env.sh` (or just confirm their `black` is up to date):
1. Confirm no functional changes
2. With the latest version of black run `black .` and confirm nothing changes
3. Run the `pre-commit run --all-files` and confirm it passes
=> Update formatting to match black

src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py, tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py
Fixes #1133
1. Check tests aren't broken
=> #1133 don't bundle screening collections with rotation scan

src/hyperion/experiment_plans/oav_grid_detection_plan.py, src/hyperion/parameters/plan_specific/gridscan_internal_params.py, src/hyperion/parameters/plan_specific/panda/panda_gridscan_internal_params.py, tests/unit_tests/experiment_plans/test_grid_detect_then_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_grid_detection_plan.py, tests/unit_tests/parameters/test_internal_parameters.py
Fixes #1118 
1. Make sure changes are sensible
2. Check new tests and changes to old ones
=> Panda grid scans: Add half a Y step to both sides of grid given an odd number of Y steps

src/hyperion/device_setup_plans/setup_zebra.py, src/hyperion/experiment_plans/flyscan_xray_centre_plan.py, src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py, src/hyperion/experiment_plans/rotation_scan_plan.py
Fixes #1142
1. Confirm all calls to zebra setup plans now wait for it to finish
=> all plans wait on zebra setup

src/hyperion/device_setup_plans/setup_panda.py, src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py, tests/conftest.py, tests/unit_tests/device_setup_plans/test_setup_panda.py, tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py
Fixes #1160 
1. Confirm velocity calculation is correct
2. Check changes to tests are correct
=> Panda grid scans: correctly work out sample velocity

setup.cfg, src/hyperion/experiment_plans/rotation_scan_plan.py, src/hyperion/external_interaction/callbacks/rotation/zocalo_callback.py, tests/conftest.py, tests/unit_tests/experiment_plans/test_rotation_scan_plan.py
Fixes #1152 and Fixes #1155
Needs a new Nexgen release for rotation scans to be processed by autoPROC; alternatively Nexgen could be pinned to main
1. Run tests
=> 1155 fix Hyperion bugs from live testing

src/hyperion/utils/context.py, tests/unit_tests/hyperion/test_main_system.py
Mitigates (but does not properly fix, see https://github.com/DiamondLightSource/hyperion/issues/1159#issuecomment-1952669379) #1159 
1. Confirm matches what's in production and makes sense
=> Do not reconnect ophyd_async devices on every plan call

src/hyperion/external_interaction/callbacks/grid_detection_callback.py, src/hyperion/external_interaction/callbacks/ispyb_callback_base.py, src/hyperion/external_interaction/callbacks/logging_callback.py, src/hyperion/external_interaction/callbacks/oav_snapshot_callback.py, src/hyperion/external_interaction/callbacks/plan_reactive_callback.py, src/hyperion/external_interaction/callbacks/rotation/ispyb_callback.py, src/hyperion/external_interaction/callbacks/rotation/nexus_callback.py, src/hyperion/external_interaction/callbacks/rotation/zocalo_callback.py, src/hyperion/external_interaction/callbacks/xray_centre/ispyb_callback.py, src/hyperion/external_interaction/callbacks/xray_centre/nexus_callback.py, src/hyperion/external_interaction/callbacks/xray_centre/zocalo_callback.py
Fixes #1170
1. Run `pyright src/hyperion/external_interaction/callbacks` on main and on here, confirm errors much reduced
=> Fix typing in callback returns

src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py, src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py, src/hyperion/external_interaction/callbacks/grid_detection_callback.py, src/hyperion/parameters/plan_specific/grid_scan_with_edge_detect_params.py, src/hyperion/parameters/plan_specific/pin_centre_then_xray_centre_params.py, src/hyperion/parameters/plan_specific/wait_for_robot_load_then_center_params.py, tests/unit_tests/experiment_plans/test_grid_detection_plan.py
Fixes #1189 
Link to dodal PR (if required): [#348](https://github.com/DiamondLightSource/dodal/pull/348)
1. Check changes are sensible
2. Tests pass
=> Correctly set run up distance

tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py, tests/unit_tests/external_interaction/ispyb/test_rotation_ispyb_store.py
=> Fix unit tests for tuple in IspybIds

setup.cfg, src/hyperion/external_interaction/nexus/write_nexus.py, tests/test_data/hyperion_parameters.json
Link to dodal PR: https://github.com/DiamondLightSource/dodal/pull/353
Removed some unused stuff and fixed some typing. 
1. Confirm unused stuff is unused and type hints are better than before
=> Removed unused parameters and fixed some typing

src/hyperion/experiment_plans/oav_grid_detection_plan.py
Adds some logs to help us diagnose edge detection issues
=> #1227 add edge logging

src/hyperion/experiment_plans/flyscan_xray_centre_plan.py, src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py
=> Wait for aperture to finish

src/hyperion/experiment_plans/oav_grid_detection_plan.py, tests/unit_tests/experiment_plans/test_grid_detection_plan.py
Fixes #1227 
1. Confirm new tests are sensible and pass
=> Fix occassional very large grids

setup.cfg, src/hyperion/external_interaction/callbacks/zocalo_callback.py, tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py, tests/unit_tests/external_interaction/callbacks/test_zocalo_handler.py
Fixes #1260
Link to dodal PR: https://github.com/DiamondLightSource/dodal/pull/383
=> Provide index to zocalo for GPU

src/hyperion/device_setup_plans/setup_panda.py, tests/unit_tests/device_setup_plans/test_setup_panda.py
Hopefully fixes #1200 , but will need to test on beamline to confirm this.
1. Confirm that new test fails without the additional wait, and passes with it.
Suggestions to make that extra test cleaner are welcome!
=> Fix occasional panda error

src/hyperion/experiment_plans/experiment_registry.py, src/hyperion/experiment_plans/robot_load_then_centre_plan.py, src/hyperion/external_interaction/callbacks/common/callback_util.py, src/hyperion/external_interaction/callbacks/common/ispyb_mapping.py, src/hyperion/external_interaction/callbacks/robot_load/ispyb_callback.py, src/hyperion/external_interaction/ispyb/exp_eye_store.py, src/hyperion/parameters/constants.py, tests/system_tests/external_interaction/test_exp_eye_dev.py, tests/test_data/parameter_json_files/good_test_robot_load_params.json, tests/test_data/test_config.cfg, tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py, tests/unit_tests/external_interaction/callbacks/robot_load/test_robot_load_ispyb_callback.py, tests/unit_tests/external_interaction/ispyb/test_expeye_interaction.py, tests/unit_tests/external_interaction/test_ispyb_utils.py
Fixes #1017
1. Confirm tests pass (including system test, which you will have to manually confirm)
=> Add ispyb entries for robot load

src/hyperion/experiment_plans/flyscan_xray_centre_plan.py, src/hyperion/experiment_plans/panda_flyscan_xray_centre_plan.py, src/hyperion/external_interaction/callbacks/rotation/nexus_callback.py, src/hyperion/external_interaction/callbacks/xray_centre/nexus_callback.py, src/hyperion/external_interaction/nexus/write_nexus.py, tests/unit_tests/external_interaction/callbacks/conftest.py, tests/unit_tests/external_interaction/callbacks/xray_centre/test_nexus_handler.py, tests/unit_tests/external_interaction/nexus/test_write_nexus.py
Fixes #1245
1. Confirm new tests pass
=> Use bit depth from the Eiger to work out datatype of gridscan VDS

src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py, src/hyperion/experiment_plans/pin_centre_then_xray_centre_plan.py, src/hyperion/parameters/components.py, src/hyperion/parameters/constants.py, src/hyperion/parameters/gridscan.py, src/hyperion/parameters/plan_specific/grid_scan_with_edge_detect_params.py, src/hyperion/parameters/plan_specific/pin_centre_then_xray_centre_params.py, src/hyperion/parameters/plan_specific/robot_load_then_center_params.py, tests/conftest.py, tests/test_data/new_parameter_json_files/good_test_grid_with_edge_detect_parameters.json, tests/test_data/new_parameter_json_files/good_test_parameters.json, tests/test_data/new_parameter_json_files/good_test_pin_centre_then_xray_centre_parameters.json, tests/test_data/new_parameter_json_files/good_test_rotation_scan_parameters_nomove.json, tests/unit_tests/experiment_plans/test_grid_detect_then_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_grid_detection_plan.py, tests/unit_tests/experiment_plans/test_pin_centre_then_xray_centre_plan.py, tests/unit_tests/parameters/plan_specific/test_grid_scan_with_edge_detect_internal_parameters.py, tests/unit_tests/parameters/plan_specific/test_rotation_internal_parameters.py, tests/unit_tests/parameters/test_parameter_model.py
part of #1275
Uses the new params for pin/grid detect and xray centre (leaves xray centre alone still)
1. Run tests
=> (#1275) convert pin and grid detect plans to new params

setup.cfg, src/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py, src/hyperion/device_setup_plans/read_hardware_for_setup.py, src/hyperion/experiment_plans/flyscan_xray_centre_plan.py, src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py, src/hyperion/experiment_plans/robot_load_then_centre_plan.py, src/hyperion/experiment_plans/rotation_scan_plan.py, src/hyperion/experiment_plans/set_energy_plan.py, src/hyperion/external_interaction/callbacks/ispyb_callback_base.py, src/hyperion/external_interaction/callbacks/rotation/nexus_callback.py, src/hyperion/external_interaction/callbacks/xray_centre/nexus_callback.py, tests/conftest.py, tests/unit_tests/device_setup_plans/test_dcm_pitch_roll_mirror_adjuster.py, tests/unit_tests/experiment_plans/conftest.py, tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_panda_flyscan_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py, tests/unit_tests/external_interaction/callbacks/conftest.py, tests/unit_tests/external_interaction/callbacks/test_rotation_callbacks.py, tests/unit_tests/hyperion/test_main_system.py
Fixes https://github.com/DiamondLightSource/dodal/issues/397
Link to dodal PR: https://github.com/DiamondLightSource/dodal/pull/461
1. Confirm unit tests pass against `dodal` branch
=> Update to use ophyd_async undulator_dcm

src/hyperion/external_interaction/ispyb/ispyb_dataclass.py, src/hyperion/parameters/components.py, src/hyperion/parameters/gridscan.py, src/hyperion/parameters/rotation.py, tests/unit_tests/parameters/test_parameter_model.py
Fixes #1102
This removes the now redundant undulator_gap from the ispyb params
1. Tests pass
=> (#1102) Remove undulator_gap from ispyb_params

tests/test_data/nexus_files/rotation/ins_8_5_expected_output.txt, tests/test_data/nexus_files/rotation_unicode_metafile/ins_8_5_expected_output.txt
Fixes the broken test_nexgen system test after the change to the omega end parameter calculation.
1. System tests pass
=> Fix for system tests after omega_end fix

src/hyperion/device_setup_plans/setup_panda.py, src/hyperion/utils/aperturescatterguard.py, tests/conftest.py, tests/system_tests/experiment_plans/test_fgs_plan.py, tests/system_tests/hyperion/test_aperturescatterguard_system.py, tests/unit_tests/device_setup_plans/test_dcm_pitch_roll_mirror_adjuster.py, tests/unit_tests/experiment_plans/test_flyscan_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_grid_detection_plan.py, tests/unit_tests/experiment_plans/test_optimise_attenuation_plan.py, tests/unit_tests/experiment_plans/test_rotation_scan_plan.py
Fixes #1405 
The changes to `optimise_attenuation` weren't actually necessary, I just missed some bits. They're cleaner now though so leaving in.
=> Fix test after dodal modules moved

setup.cfg, src/hyperion/experiment_plans/optimise_attenuation_plan.py, tests/system_tests/external_interaction/callbacks/test_external_callbacks.py
Fixes https://github.com/DiamondLightSource/dodal/issues/416
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/480
1. Ensure tests are passing
=> Update to new ophyd_async shutter

setup.cfg, src/hyperion/device_setup_plans/manipulate_sample.py, src/hyperion/experiment_plans/grid_detect_then_xray_centre_plan.py, tests/unit_tests/experiment_plans/test_grid_detect_then_xray_centre_plan.py
Fixes https://github.com/DiamondLightSource/dodal/issues/602
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/603
=> Change backlight to ophyd_async

tests/system_tests/external_interaction/test_ispyb_dev_connection.py
Fixes #1441
1. Run the tests in `test_ispyb_dev_connection.py` and confirm they now pass
=> Fix ispyb dev tests

tests/conftest.py, tests/system_tests/external_interaction/test_ispyb_dev_connection.py, tests/unit_tests/experiment_plans/test_rotation_scan_plan.py
Fixes failing tests from https://github.com/DiamondLightSource/dodal/pull/591
1. Pull latest `dodal`
2. Confirm tests fail on main
3. Confirm tests pass on this branch
=> Fix changes to synchrotron device

setup.cfg, tests/unit_tests/experiment_plans/test_grid_detection_plan.py
Adding thumbnail snapshots broke a test which checks the number of snapshots saved
=> fix snapshot test for thumbnail

src/hyperion/experiment_plans/robot_load_then_centre_plan.py, src/hyperion/external_interaction/callbacks/__main__.py, src/hyperion/external_interaction/callbacks/robot_load/ispyb_callback.py, tests/unit_tests/experiment_plans/test_wait_for_robot_load_then_centre.py, tests/unit_tests/external_interaction/callbacks/robot_load/test_robot_load_ispyb_callback.py, tests/unit_tests/external_interaction/callbacks/test_external_callbacks.py
Fixes https://github.com/DiamondLightSource/hyperion/issues/1446
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/629
1. Confirm all points in issue are addressed by this PR or subsequent issues
=> 1446 robot load fixes

setup.cfg
1. Confirm dodal version properly pinned
=> Updated dodal version

src/hyperion/utils/context.py, tests/unit_tests/hyperion/test_main_system.py
=> Remove override for faking devices

tests/conftest.py
See https://github.com/DiamondLightSource/dodal/issues/690
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/747
=> Remove unused qbpm
